### ISSUE TITLE
Не работает мониторинг лицензий. Windows server 2019. Платформа 1c 8.3.21.1622

### ISSUE THREAD

**Issue by Tiotimolin** [slothfk/1c_zabbix_template_ce#101]
Приветствую, Алексей.
3-ий день не могу победить мониторинг сервера лицензирования.
Windows server 2019. Платформа 1c 8.3.21.1622
Делаю всё по инструкции:
1. Установил GitBash.
2. Установил ring и установил Java 8.
3. Добавил службу RAS
4. Добавил в C:\Program Files\Zabbix Agent\zabbix_agentd.conf

UserParameter=1c.ls.sessions[*],"C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent\scripts\1c_license_server.sh" used $1 $2 $3 $4
UserParameter=1c.ls.check[*],"C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent\scripts\1c_license_server.sh" check
UserParameter=1c.ls.clusters.discovery[*],"C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent\scripts\1c_license_server.sh" clusters
UserParameter=1c.ls.infobases.discovery[*],"C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent\scripts\1c_license_server.sh" infobases $1 $2 $3 $4

5. Положил скрипты в папку C:\Program Files\Zabbix Agent\scripts\

1c_central_server.sh
1c_common_module.sh
1c_license_server.sh
1c_ls_license_info.sh
1c_work_server.sh

6. Изменил содержимое 1c_ls_license_info.sh по совету в одной из ветки запросов.
#!/bin/bash
"/c/Program Files/Zabbix Agent/zabbix_sender.exe" -c "/c/Program Files/Zabbix Agent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/Zabbix\ Agent/Scripts/1c_license_server.sh info)" > /dev/null

7. Активные проверки включены, Hostname прописан, другие шаблоны данные собирают.

8. Запуск вручную
$ "/c/Program Files/Zabbix Agent/zabbix_sender.exe" -c "/c/Program Files/Zabbix Agent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/Zabbix\ Agent/Scripts/1c_license_server.sh info)" > /dev/null
выдаёт
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
zabbix_sender.exe [1244]: too few or mutually exclusive options used

9. Вывод $ bash -x 1c_license_server.sh info
++ dirname 1c_license_server.sh
++ sed -r 's/\\/\//g; s/^(.{1}):/\/\1/'
+ WORK_DIR=.
+ source ./1c_common_module.sh
+ case ${1} in
+ licenses_summary
++ check_ring_license
++ [[ -z 1 ]]
++ RING_CONF=/C/ProgramData/1C/1CE/ring-commands.cfg
++ [[ ! -f /C/ProgramData/1C/1CE/ring-commands.cfg ]]
+++ grep license-tools /C/ProgramData/1C/1CE/ring-commands.cfg
+++ sed -r 's/.+file: //; s/\\/\//g; s/^(.{1}):/\/\1/'
++ LIC_TOOL='/C/Program Files/1C/1CE/components/1c-enterprise-license-tools-0.15.0+2-x86_64/com._1c.license.activator.ring-0.15.0-2.jar'
++ [[ -z /C/Program Files/1C/1CE/components/1c-enterprise-license-tools-0.15.0+2-x86_64/com._1c.license.activator.ring-0.15.0-2.jar ]]
++ ls '/C/Program Files/1C/1CE/components/1c-enterprise-ring-0.19.5+12-x86_64/ring.cmd'
+ RING_TOOL='/C/Program Files/1C/1CE/components/1c-enterprise-ring-0.19.5+12-x86_64/ring.cmd'
+ export RING_TOOL
+ awk 'BEGIN { files=0; users=0 }
            { files+=1; users+=$1 }
            END { print files":"users }'
++ get_license_list '/C/Program Files/1C/1CE/components/1c-enterprise-ring-0.19.5+12-x86_64/ring.cmd'
++ '/C/Program Files/1C/1CE/components/1c-enterprise-ring-0.19.5+12-x86_64/ring.cmd' license list --send-statistics false
++ sed -re 's/^([0-9\-]+).*/\1/'
+ execute_tasks license_info $'382023987945447-8102223133\350\354\377' $'\364\340\351\353\340:' '"20221206181817.lic")' $'298892234985059-8101653947\350\354\377' $'\364\340\351\353\340:' '"20221229202653.lic")' $'262088225830297-8101673256\350\354\377' $'\364\340\351\353\340:' '"20221229202855.lic")'
+ [[ 10 -le 1 ]]
+ TASK_CMD=license_info
+ shift
+ export -f license_info
+ echo $'382023987945447-8102223133\350\354\377' $'\364\340\351\353\340:' '"20221206181817.lic")' $'298892234985059-8101653947\350\354\377' $'\364\340\351\353\340:' '"20221229202653.lic")' $'262088225830297-8101673256\350\354\377' $'\364\340\351\353\340:' '"20221229202855.lic")'
+ xargs '-d ' -P2 -I task_args bash -c 'license_info ${@}' _ task_args
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
0:0

Также в заббиксе:

[1С/Лицензии] Количество лицензированных сеансов
Preprocessing failed for:
1. Failed: cannot perform regular expression "\d+:(\d+)" match for value of type "string": pattern does not match

	
[1С/Лицензии] Количество файлов пользовательски..
Preprocessing failed for:
1. Failed: cannot perform regular expression "(\d+):\d+" match for value of type "string": pattern does not match

Подскажите, пожалуйста, куда копать?
![Untitled](https://user-images.githubusercontent.com/125429021/218932785-019d5b8e-37e4-4ccb-a22a-851fc0b4a4df.jpg)

**Comment by slothfk** [comment]
Давайте разберемся "с малым" - подсчетом сеансов, потребляющих лицензии
Что на серевере лицензирования возвращает (необходимо выполнять от имени пользователя с административными правами, или такими правами, которые позволяют посмотреть список процессов других пользователей)
```
$ bash 1c_license_server.sh sessions 1545 1.5 <пользователь_администратор_кластера> <пароль администратора кластера>
```
`<пользователь_администратор_кластера>` и `<пароль администратора кластера>` необходимо указывать только если они заданы

**Comment by Tiotimolin** [comment]
$ bash 1c_license_server.sh sessions 1545 1.5
ОШИБКА: Неизвестный режим работы скрипта!

**Comment by slothfk** [comment]
Ох, пардон, конечно надо так
```
$ bash 1c_license_server.sh used 1545 1.5
```

**Comment by Tiotimolin** [comment]
$ bash 1c_license_server.sh used 1545 1.5
CL#5ea92056-4f6e-4b9c-93da-f7f8ef473a66:0:0:0:0:0
CL#555726a9-04fc-4f23-af37-bc564d9c3aca:0:0:0:0:0
CL#6de36e3a-dd57-47ff-ba61-d7bcb3f42bf4:0:0:0:0:0
CL#53e383a9-fc34-440d-b93c-b681a3bdb68f:0:0:0:0:0
CL#b883cd3f-2d86-4953-9e03-f544f37561b4:0:0:0:0:0
CL#d9a7fe3a-66e4-4871-9a88-b8dda5d1f293:0:0:0:0:0
CL#f5a6ab3f-ba96-48f6-b714-1ba2aad27881:0:0:0:0:0
summary:0:0:0:0:0

**Comment by slothfk** [comment]
Администратор кластера есть?

**Comment by Tiotimolin** [comment]
При запуске с логином паролем сервера 1с, а это сервер лицензирования

$ bash 1c_license_server.sh used 1545 1.5 USER1C XXXXXXXXXXXXXXXXXXXX
CL#5ea92056-4f6e-4b9c-93da-f7f8ef473a66:0:0:0:0:0
CL#555726a9-04fc-4f23-af37-bc564d9c3aca:0:0:0:0:0
CL#d9a7fe3a-66e4-4871-9a88-b8dda5d1f293:0:0:0:0:0
CL#53e383a9-fc34-440d-b93c-b681a3bdb68f:0:0:0:0:0
CL#f5a6ab3f-ba96-48f6-b714-1ba2aad27881:0:0:0:0:0
CL#b883cd3f-2d86-4953-9e03-f544f37561b4:0:0:0:0:0
CL#6de36e3a-dd57-47ff-ba61-d7bcb3f42bf4:0:0:0:0:0

И висит....

**Comment by slothfk** [comment]
> с логином паролем сервера 1с

что это значит? речь про администратора кластера, который добавляется у конкретного кластера (в консоли кластера), если его на задавали, то указывать пользователя здесь не надо, если  задан, то должен быть одинаковым для всех кластеров

**Comment by Tiotimolin** [comment]
$ bash 1c_license_server.sh used 1545 1.5 USER1C XXXXXXXXXX
CL#5ea92056-4f6e-4b9c-93da-f7f8ef473a66:0:0:0:0:0
CL#555726a9-04fc-4f23-af37-bc564d9c3aca:0:0:0:0:0
CL#53e383a9-fc34-440d-b93c-b681a3bdb68f:0:0:0:0:0
CL#f5a6ab3f-ba96-48f6-b714-1ba2aad27881:0:0:0:0:0
CL#6de36e3a-dd57-47ff-ba61-d7bcb3f42bf4:0:0:0:0:0
CL#b883cd3f-2d86-4953-9e03-f544f37561b4:0:0:0:0:0
CL#d9a7fe3a-66e4-4871-9a88-b8dda5d1f293:0:0:0:0:0
summary:0:0:0:0:0

**Comment by Tiotimolin** [comment]
[[1С/Лицензии] Активные сеансы] с ошибкой
Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.

**Comment by slothfk** [comment]
в пароле используеются "недопустимый" символ ... если без этого символа никак, то надо отключать проверку в настройках агента заббикс, либо сменить пароль

**Comment by Tiotimolin** [comment]
Такое простое решение )))
Благодарю, Алексей.
![image](https://user-images.githubusercontent.com/125429021/218955348-7422c688-5954-4236-bdc8-92c9b0fef1c5.png)

Хорошего дня вам )))))

**Comment by Tiotimolin** [comment]
Прошу прощения, а есть какой-то параметр, который отвечает за частоту опросов кол-ва лицензий?
Или нужно в шедулер добавлять?

**Comment by slothfk** [comment]
> Прошу прощения, а есть какой-то параметр, который отвечает за частоту опросов кол-ва лицензий? Или нужно в шедулер добавлять?

Если речь про файлы лицензий, то да, это надо добавить в планировщик задач

Есть мысли переделать этот механизм, но по срокам пока не сориентирую :/

**Comment by Tiotimolin** [comment]
Алексей, странное дело.
Данные отобразились один раз и больше в забихе не обновляются.
В планировщик добавил.
Рестартовал агента, рестартил службу 1с
В баше данные читает.

$ bash 1c_license_server.sh used 1545 1.5 USER1C XXXXXXXXXXXXXXXXXXXX
CL#5ea92056-4f6e-4b9c-93da-f7f8ef473a66:0:10:19:0:0
CL#53e383a9-fc34-440d-b93c-b681a3bdb68f:15:12:15:0:0
CL#555726a9-04fc-4f23-af37-bc564d9c3aca:34:17:35:1:0
CL#f5a6ab3f-ba96-48f6-b714-1ba2aad27881:6:18:21:15:0
CL#d9a7fe3a-66e4-4871-9a88-b8dda5d1f293:15:8:15:0:0
CL#6de36e3a-dd57-47ff-ba61-d7bcb3f42bf4:7:5:9:2:0
CL#b883cd3f-2d86-4953-9e03-f544f37561b4:0:0:0:0:0
summary:77:67:114:18:0

Что я делаю не так?
Извините за назойливость ((

![image](https://user-images.githubusercontent.com/125429021/219029782-b3280f34-370d-4d84-bacf-5d45891ce281.png)

**Comment by slothfk** [comment]
> bash 1c_license_server.sh used 1545 1.5 USER1C XXXXXXXXXX - эту ведь строку надо в шедулер засовывать?

нет в планировщик надо другое - `1c_ls_license_info.sh` пихать

**Comment by slothfk** [comment]
> Данные отобразились один раз и больше в забихе не обновляются.

что в журналах агента и сервера **zabbix** есть?

**Comment by Tiotimolin** [comment]
В логах агента:
  6416:20230215:155955.876 IPv6 support:          YES
  6416:20230215:155955.877 TLS support:           YES
  6416:20230215:155955.878 **************************
  6416:20230215:155955.879 using configuration file: C:\Program Files\Zabbix Agent\zabbix_agentd.conf
  6416:20230215:155956.880 agent #0 started [main process]
  7684:20230215:155956.881 agent #1 started [collector]
   960:20230215:155956.882 agent #3 started [listener #2]
 12704:20230215:155956.884 agent #4 started [listener #3]
 14524:20230215:155956.886 agent #5 started [active checks #1]
  5960:20230215:155956.887 agent #2 started [listener #1]

В заббиксе при попытке выполнить итем
![image](https://user-images.githubusercontent.com/125429021/219034735-477dba9e-1853-40e1-922d-3358a0393936.png)

В баше при попытке выполнить вручную

$ ./1c_ls_license_info.sh
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
zabbix_sender.exe [5236]: too few or mutually exclusive options used

Содержимое скрипта:
#!/bin/bash

"/c/Program Files/Zabbix Agent/zabbix_sender.exe" -c "/c/Program Files/Zabbix Agent/zabbix_agentd.conf" -k 1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/Zabbix\ Agent/Scripts/1c_license_server.sh info)" > /dev/null

**Comment by Tiotimolin** [comment]
Удалил всё, настроил заново.
Работает. Благодарю.

**Comment by sanykz** [comment]
помогите разобраться! Сделал все по шаблонам. 
но - не могу получить информацию о лицензиях
<img width="1081" alt="Снимок экрана 2024-05-21 в 10 56 06" src="https://github.com/slothfk/1c_zabbix_template_ce/assets/170390534/85f7b555-befa-44cc-8a55-6b2f3aff8a36">

Когда запускаю вручную 
"/c/Program Files/ZabbixAgent/zabbix_sender.exe" -c "/c/Program Files/ZabbixAgent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/ZabbixAgent/Scripts/1c_license_server.sh used)" > /dev/null



$ "/c/Program Files/ZabbixAgent/zabbix_sender.exe" -c "/c/Program Files/ZabbixAgent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/ZabbixAgent/Scripts/1c_license_server.sh used)" > /dev/null
bash: 1c.ls.licenses: Permission denied

$ "/c/Program Files/ZabbixAgent/zabbix_sender.exe" -c "/c/Program Files/ZabbixAgent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/ZabbixAgent/Scripts/1c_license_server.sh info)" > /dev/null
ОШИБКА: Неизвестный режим работы скрипта!
bash: 1c.ls.licenses: Permission denied

**Comment by slothfk** [comment]
> помогите разобраться! Сделал все по шаблонам. но - не могу получить информацию о лицензиях <img alt="Снимок экрана 2024-05-21 в 10 56 06" width="1081" src="https://private-user-images.githubusercontent.com/170390534/332277882-85f7b555-befa-44cc-8a55-6b2f3aff8a36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTY0NTgsIm5iZiI6MTcxNjM1NjE1OCwicGF0aCI6Ii8xNzAzOTA1MzQvMzMyMjc3ODgyLTg1ZjdiNTU1LWJlZmEtNDRjYy04YTU1LTZiMmYzYWZmOGEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNTM1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDRhNjk0MjdkMWRlMzIyNmFkNjcyNzRkNDEwYTJmZmIzNTkzN2Y4ZTBhMTc2OGY2MjJiNmQ5Y2UxZTA2YmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9OGdDnYKWnFxG6MLZVUC9xBYBe5i7FNbKEF9_qgv8ck">
> 
> Когда запускаю вручную "/c/Program Files/ZabbixAgent/zabbix_sender.exe" -c "/c/Program Files/ZabbixAgent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/ZabbixAgent/Scripts/1c_license_server.sh used)" > /dev/null
> 
> $ "/c/Program Files/ZabbixAgent/zabbix_sender.exe" -c "/c/Program Files/ZabbixAgent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/ZabbixAgent/Scripts/1c_license_server.sh used)" > /dev/null bash: 1c.ls.licenses: Permission denied
> 
> $ "/c/Program Files/ZabbixAgent/zabbix_sender.exe" -c "/c/Program Files/ZabbixAgent/zabbix_agentd.conf" -k >1c.ls.licenses -o "$(nice -n 19 /c/Program\ Files/ZabbixAgent/Scripts/1c_license_server.sh info)" > /dev/null ОШИБКА: Неизвестный режим работы скрипта! bash: 1c.ls.licenses: Permission denied

Все что вы написали так не работает! И потом, у вас ошибка в команде, поэтому выдает
> bash: 1c.ls.licenses: Permission denied
у после `-k` лишний символ `>`
Для того чтобы иметь информацию о лицензиях (фалах лицензий) используется скрипт `1c_license_files.sh`, а не `1c_license_server.sh`

**Comment by sanykz** [comment]
"у после -k лишний символ >" Поправил. 
Извините, я так и не понял. Где у меня затык.... 
На  metric так и ругается

<img width="1051" alt="image" src="https://github.com/slothfk/1c_zabbix_template_ce/assets/170390534/15b1e63e-d799-4cd1-ab95-34e1671d5538">
<img width="1071" alt="image" src="https://github.com/slothfk/1c_zabbix_template_ce/assets/170390534/c93e75a5-6b09-4059-b769-ea5f6b3eee50">

<img width="1078" alt="image" src="https://github.com/slothfk/1c_zabbix_template_ce/assets/170390534/6b08021e-1731-4ed9-9d43-918595e2e553">

и пустые данные:
<img width="936" alt="image" src="https://github.com/slothfk/1c_zabbix_template_ce/assets/170390534/9040762c-3aeb-4a29-8dad-94f2aa514445">

**Comment by sanykz** [comment]
Я кажется просто запутался( 
Какие действия делаются на Zabbix server (Linux), какие действия на 1с (Windows)

**Comment by sanykz** [comment]
> > bash 1c_license_server.sh использовал 1545 1.5 USER1C XXXXXXXXXX - эту строку нужно в шедулер засовывать?
> 
> нет в планировщик надо другое - `1c_ls_license_info.sh` пихать

1c_ls_license_info.sh - где всять данный скрипт для win? я не нашел....

**Comment by slothfk** [comment]
> 1c_ls_license_info.sh - где всять данный скрипт для win? я не нашел....

Это уже не актуально. Было сделано изменение в структуре шаблона и теперь нет необходимости настраивать регламенты на хосте, мониторинг которого выполняется

**Comment by sanykz** [comment]
> > 1c_ls_license_info.sh - где весь данный скрипт для победы? я не нашел...
> 
> Это уже не актуально. Было сделано изменение в структуре шаблона, и теперь нет необходимости настраивать регламенты на хосте, мониторинг которого выполняется

Тогда я где то запутался(


- все скрипты из каталога scripts (в каталог C:\Program Files\ZabbixAgent\scripts) перенес
- все файлы userparameter_1c-*.conf из каталога configs в кататалог C:\Program Files\ZabbixAgent\zabbix_agent2.d  перенес.
- RAS запустил
[1С/Центральный сервер] Статус сервиса RAS 24с	Up (1)
- создал каталог для файлов технологического журнала, в шаблоне указал.
Информация худо бедно начала собираться.
Но, количество активных сеансов 0. Хотя база открыта, работа ведется и тд. 
А все показатели 0?

1c_clusters_cache_monitoring - пустой
1c_clusters_cache_1545: ххххххх:1545#ххххххххххххххххх,1541,"Локальный кластер"; есть информация
1c_infobase_cache - пустой
1c_rphost_pid_hash - есть информация


$ bash 1c_license_server.sh used 1545 1.5 user pass
LIC#20250160600.lic:0
LIC#2025033603.lic:0
summary:0:0:0:0:0

![Image](https://github.com/user-attachments/assets/a0d15630-fd28-4a0d-af3a-1d0a698e59cb)
![Image](https://github.com/user-attachments/assets/cd1fd2d6-523c-43ec-bb22-db16f90581b0)
![Image](https://github.com/user-attachments/assets/028c40cb-0b6c-4ff3-9b04-248d677e7901)


$ hostname
SAXXXX61

![Image](https://github.com/user-attachments/assets/b31838fb-ff3c-46b3-9ab2-5b608899d4c4)

![Image](https://github.com/user-attachments/assets/8189d737-7564-48bd-ad77-98d012cb529a)

Имена совпадают
