### ISSUE TITLE
Не работает discovery

### ISSUE THREAD

**Issue by Diesel315** [slothfk/1c_zabbix_template_ce#103]
Добрый день!

Мы с вами общались относительно недавно, решали проблему с кодировкой и прочими мелочами.
В целом тогда все вопросы закрыли и все работало относительно нормально. В какой-то момент, к сожалению, не могу отследить когда именно (в причинно-следственной части), перестал работать discovery.
Основные параметры работают.
![image](https://user-images.githubusercontent.com/19303933/233059957-8307296b-452c-4aa4-9e07-d5ebdaad34bb.png)
Поиск по базам нет
![image](https://user-images.githubusercontent.com/19303933/233060120-1fb811f0-f8e9-4e50-a61b-71bb812f8535.png)
По элементам данных такая ошибка
![image](https://user-images.githubusercontent.com/19303933/233060370-c61d07d2-76e9-44c6-88bc-8038118ec7b8.png)
![image](https://user-images.githubusercontent.com/19303933/233060427-c04796a8-6807-457f-8c32-ea3fc47a13fc.png)
Можете подсказать по проблеме?
Отслеживаю сервер лицензирования.

**Comment by slothfk** [comment]
> ![image](https://user-images.githubusercontent.com/19303933/233060427-c04796a8-6807-457f-8c32-ea3fc47a13fc.png)
> Можете подсказать по проблеме?

Исходя из этой картинки Вы можете сделать вывод когда "все отвалилось", так как период хранения "утерянных" значений - 30 дней, у вас осталось хранить 28 дней

Пропали данные по всем информационным базам или только по одной (в рамках одного кластера)?

**Comment by Diesel315** [comment]
Доброе.
Ситуация. Я все удалил и сделал заново. Поэтому истории в глубину нет.
Из текущей ситуации, видно что данные иногда прорываются
![image](https://user-images.githubusercontent.com/19303933/233535815-1c4afa9f-cfa4-40c3-a714-2f46957cc109.png)
![image](https://user-images.githubusercontent.com/19303933/233535888-141eea41-a193-4d6e-a04d-641b79220fc1.png)
Проблема по всем базам.

**Comment by slothfk** [comment]
таймаут в макросе **{$RAS_TIMEOUT}** какой стоит?
у агента заббикса какой таймаут?

**Comment by Diesel315** [comment]
{$RAS_TIMEOUT} - 3.0
Агент - Timeout=30

**Comment by slothfk** [comment]
> {$RAS_TIMEOUT} - 3.0

Пришлите выполненную в git bash команду
```
$ time rac cluster list <адрес_любого_центрального_сервера>
```
У коллеги тут **ras** спискок кластеров за **4.5** секунды отдает, так что `{$RAS_TIMEOUT}` в данном случае должен быть не меньше 5 сек.

**Comment by slothfk** [comment]
А у вас не та же история, что здесь https://github.com/slothfk/1c_zabbix_template_ce/issues/109#issuecomment-1560849021?

**Comment by slothfk** [comment]
Актуально ли?
