### ISSUE TITLE
Проблема с отображением общего количества сеансов

### ISSUE THREAD

**Issue by MegaShIzoID** [slothfk/1c_zabbix_template_ce#105]
Два центральных сервера в кластере. Режим отказоустойчивости - 0. В случае с базами все замечательно - правильно отображается количество сеансов для каждой базы.
А вот общее количество показывает в два раза больше, для любых видов заданий, как для фоновых, так и для общего количества. Оно конечно решается добавлением множителя 0.5 в предобработку элемента данных, но по мне так не особо красивый выход.
![image](https://user-images.githubusercontent.com/20921558/233941837-500132d1-c658-4d06-a3ff-7aa1a20fdb43.png)

UPD: у шаблона лицензий точно такое же поведение, количество уникальных пользователей отображается нормально, а вот общее количество сеансов, количество выданных лицензий, количество лицензий на клиенте и количество веб-клиентов - удваивает. Подозреваю что это связано с вышеописанными двумя центральными серверами, но проверить подозрение не могу.

**Comment by slothfk** [comment]
А по кластерам как? Скриншот из центрального сервера?

**Comment by MegaShIzoID** [comment]
> А по кластерам как? Скриншот из центрального сервера?

я повесил шаблон на один сервер кластера только, скриншот с него, да

**Comment by slothfk** [comment]
> А по кластерам как? Скриншот из центрального сервера?

я имел ввиду, если включить обнаружение кластеров, то по ним показатели не удвоенные будут?

**Comment by MegaShIzoID** [comment]
> я имел ввиду, если включить обнаружение кластеров, то по ним показатели не удвоенные будут?

включил, показывает действительные значения, без удвоения
![image](https://user-images.githubusercontent.com/20921558/234182833-14a37388-931e-40e4-a9b5-ad1926ff0e9c.png)
общее количество сеансов (не кластера) в данном случае с множителем 0,5 в предобработке

**Comment by slothfk** [comment]
> общее количество сеансов (не кластера) в данном случае с множителем 0,5 в предобработке

Хм, странно ... Но спасибо, проверю!
Говорите и на центральном и на лицензировании так?

**Comment by MegaShIzoID** [comment]
> Хм, странно ... Но спасибо, проверю! Говорите и на центральном и на лицензировании так?

![image](https://user-images.githubusercontent.com/20921558/234184065-2d517c14-dfd9-43cb-9623-735589a2960a.png)
Вот так показывает если с дефолтными настройками все оставить, без всяких кастомных предобработок и прочего

**Comment by MegaShIzoID** [comment]
> Правильно ли я понимаю, что на центральном сервере одна база и один кластер?

один кластер, два центральных сервера, рабочих нет, баз - 14, активно используются 4

**Comment by slothfk** [comment]
Тогда все последние данные по всем элементам данных, в которых в названии есть "Общее количество сеансов" покажите пожалуйста

**Comment by MegaShIzoID** [comment]
> Тогда все последние данные по всем элементам данных, в которых в названии есть "Общее количество сеансов" покажите пожалуйста

![image](https://user-images.githubusercontent.com/20921558/234251219-c235e622-5f26-4717-a650-b2bb745a14f3.png)

в остальных базах нет пользователей, это копии, тестовые и тд. ну и собственно деактивированы они в шаблоне

**Comment by MegaShIzoID** [comment]
ради проверки я полностью отключил все три шаблона с очисткой данных, подключил только шаблон центрального сервера и вот такое, причем первый раз он показывает правильное количество, потом через несколько опросов значение удваивается и остается уже таким

**Comment by MegaShIzoID** [comment]
![image](https://user-images.githubusercontent.com/20921558/234460373-7aa4877f-2e08-470c-b186-173e14bac33d.png)
замазал только фамилию пользователя, общее количество сеансов в заббиксе на данный момент показывает 136

**Comment by slothfk** [comment]
при этом в заббиксе 246 общее число сеансов показывает?

**Comment by MegaShIzoID** [comment]
иногда получает действительное количество, но не всегда
![image](https://user-images.githubusercontent.com/20921558/234511555-edac7b41-2305-40f5-a45e-0b55609d53e8.png)

**Comment by slothfk** [comment]
очень интересно ...

**Comment by slothfk** [comment]
а включите, пожалуйста, у наблюдаемого узла в элементе данных `[1C/Центральный сервер] Текущие сеансы` историю хранения, скажем 1 час
![изображение](https://user-images.githubusercontent.com/16452185/234749324-3080c014-6b61-49d6-8fc2-02b1203e5047.png)
И пришлите последние данные по данному элементу, когда отображается удвоенное значение общего количества сеансов

**Comment by MegaShIzoID** [comment]
> а включите, пожалуйста, у наблюдаемого узла в элементе данных `[1C/Центральный сервер] Текущие сеансы` историю хранения, скажем 1 час ![изображение](https://user-images.githubusercontent.com/16452185/234749324-3080c014-6b61-49d6-8fc2-02b1203e5047.png) И пришлите последние данные по данному элементу, когда отображается удвоенное значение общего количества сеансов

ну вот то что он насобирал за 13 минут, если недостаточно будет то могу больше насобирать
https://gist.github.com/MegaShIzoID/b5377eb95af53a929472da281f89b36d

**Comment by slothfk** [comment]
> ну вот то что он насобирал за 13 минут, если недостаточно будет то могу больше насобирать
> https://gist.github.com/MegaShIzoID/b5377eb95af53a929472da281f89b36d

Спасибо, этого достаточно! Подскажите, а сколько процессов **rmgnr** на этом сервере? И какие у них параметры запуска?

**Comment by MegaShIzoID** [comment]
> Спасибо, этого достаточно! Подскажите, а сколько процессов **rmgnr** на этом сервере? И какие у них параметры запуска?

процессы все по одному, rmngr, rphost, ras и ragent
служба сервера запускается вот так
"C:\Program Files\1cv8\current\bin\ragent.exe" -srvc -agent -regport 1541 -port 1540 -range 1560:1591 -d "C:\Program Files\1cv8\srvinfo"
или я неправильно понял про параметры?

**Comment by slothfk** [comment]
> или я неправильно понял про параметры?

все правильно, только я хотел для процесса **rmngr**, но наверное не суть, если процесс один :/
пока идей нет ... странно как-то ...

**Comment by slothfk** [comment]
а что вернет команда, запущенная под административными правами из **git bash**
```
$  wmic path win32_process where "caption like 'rphost%'" get CommandLine | grep rphost | 
    sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/' | sort -u |
    awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
        else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
        END { for ( i in clstr_list ) { print i":"clstr_list[i]} }''
```

**Comment by MegaShIzoID** [comment]
> а что вернет команда, запущенная под административными правами из **git bash**
> 
> ```
> $  wmic path win32_process where "caption like 'rphost%'" get CommandLine | grep rphost | 
>     sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/' | sort -u |
>     awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
>         else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
>         END { for ( i in clstr_list ) { print i":"clstr_list[i]} }''
> ```

просит ввести еще что-нибудь
![image](https://user-images.githubusercontent.com/20921558/234759460-dc7f9857-26d3-4baf-a899-3ed1c06a6ded.png)

**Comment by slothfk** [comment]
> просит ввести еще что-нибудь

затесался лишний символ `'` в последней строке

> УПД если выполнить до sort -u то пишет
> 1CSERVER:1541

Еще больше интересно ... Агент **zabbix** от системной учетки запускается? Посмотреть бы содержимое файла `1c_clusters_cache` для пользователя под которым запускается агент **zabbix** (должен быть где-то в каталоге временных файлов пользователя)

**Comment by MegaShIzoID** [comment]
> Еще больше интересно ... Агент **zabbix** от системной учетки запускается? Посмотреть бы содержимое файла `1c_clusters_cache` для пользователя под которым запускается агент **zabbix** (должен быть где-то в каталоге временных файлов пользователя)

нашелся в двух местах
![image](https://user-images.githubusercontent.com/20921558/234765855-fd920304-7123-4ad0-9553-dc71114dc4a3.png)
 в темпе пользователя "Администратор" одна запись про кластер, а в виндовом темпе две одинаковых, заббикс-агент запускается от системного пользователя, а вот агент сервера от отдельно созданного

**Comment by slothfk** [comment]
> Содержимое виндового, потому что админский это как я понял от ручных запусков появился
> ![image](https://user-images.githubusercontent.com/20921558/234770101-50dbeb5e-7851-4d8d-8e0d-0afe279fd08d.png)

Удалите этот файл и посмотрите когда появится, опять будет две строки?

**Comment by MegaShIzoID** [comment]
> > Содержимое виндового, потому что админский это как я понял от ручных запусков появился
> > ![image](https://user-images.githubusercontent.com/20921558/234770101-50dbeb5e-7851-4d8d-8e0d-0afe279fd08d.png)
> 
> Удалите этот файл и посмотрите когда появится, опять будет две строки?

да, после появления файла опять две строки

**Comment by MegaShIzoID** [comment]
ну и если это важно то заббикс 6.4.1, заббикс агент 2 и Windows server 2008 r2

**Comment by slothfk** [comment]
пока я затрудняюсь сказать откуда берется вторая строка и почему ее нет при ручном запуске!?

**Comment by MegaShIzoID** [comment]
> пока я затрудняюсь сказать откуда берется вторая строка и почему ее нет при ручном запуске!?

Конкретно в моем случае помогло заменить в данном месте >> на >
![image](https://user-images.githubusercontent.com/20921558/234780716-7619775e-4bd7-4195-9adc-7e483c888ccd.png)
файл 1c_common_module.sh

**Comment by slothfk** [comment]
> Конкретно в моем случае помогло заменить в данном месте >> на >, но как я понял это не сработает в случае нескольких кластеров на сервер

Все верно, в случае нескольких кластеров все поломается :(

Все равно не понятно откуда возникает дубль, при чем только в случае запуска агентом **zabbix**!?

**Comment by slothfk** [comment]
![изображение](https://user-images.githubusercontent.com/16452185/234788464-80e27519-1412-4052-b1d9-562bc67360e9.png)
а вставьте такую строчу в `1c_common_module.sh` и потом пришлите содержимое `1c_rmngr_list`

**Comment by MegaShIzoID** [comment]
> ![изображение](https://user-images.githubusercontent.com/16452185/234788464-80e27519-1412-4052-b1d9-562bc67360e9.png) а вставьте такую строчу в `1c_common_module.sh` и потом пришлите содержимое `1c_rmngr_list`

![image](https://user-images.githubusercontent.com/20921558/234794571-115e45cc-0d14-4e56-a4c3-cc810d9dd02d.png)

в общем дело было не в бобине, как я понимаю, в конфиге заббикса в параметре ServerActive был указан и айпишник и доменное имя сервера мониторинга, оставил только айпишник и все стало отображаться по-человечески. не совсем понятно конечно такое поведение, но вот так получилось. Извиняюсь за потраченое время.

**Comment by slothfk** [comment]
> в общем дело было не в бобине, как я понимаю, в конфиге заббикса в параметре ServerActive был указан и айпишник и доменное имя одного и того же сервера мониторинга, оставил только айпишник и все стало отображаться по-человечески. не совсем понятно конечно такое поведение, но вот так получилось

Все равно странно, по идее файл должен очищаться каждым экземпляром скрипта ... хотя, учитывая задержку при получении ответа от RAS, возможно такое поведение ...

Наверное стоит подумать как предотвратить подобные "коллизии" :/
