### ISSUE TITLE
Проблема с работой из под windows

### ISSUE THREAD

**Issue by Staddou** [slothfk/1c_zabbix_template_ce#106]
Пытались раскатить под windows 
Столкнулись со следующими проблемами:

1) Скрипт не определял tmp папку для windows.
Поправили тем, что просто явно указали путь до "/c/Windows/Temp" в файле 1c_common_module.sh

2) Авторизация не работала. 
Была необходимость в использовании локальной учетки. 
Zabbix запрещает отправлять символ \ поэтому так же в 1c_common_module.sh изменили строку в функции make_ras_params
 [[ -n ${3} ]] && RAS_AUTH="--cluster-user=.\\${3}"

После данных преобразований все заработало. 
Спасибо большое за проект!

**Comment by slothfk** [comment]
> 1. Скрипт не определял tmp папку для windows.
>        Поправили тем, что просто явно указали путь до "/c/Windows/Temp" в файле 1c_common_module.sh

А как это проявлялось? Какая-то ошибка?

**Comment by Staddou** [comment]
Файл отсутсвовал.
