### ISSUE TITLE
Ошибка элементов данных 1С/Кластер

### ISSUE THREAD

**Issue by MegaShIzoID** [slothfk/1c_zabbix_template_ce#110]
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/78316550-01db-4bfe-9ac5-8d9f1b99cebb)
обновил сегодня шаблон, скрипты и конфиги, появились ошибки для элементов данных, заметил расхождения между данными что получаются с кластера и строкой разбора
с кластера прилетает: CL#37a38f89-b3e1-4022-b433-b9aeec728544:45:41:60:15:3
а шаблон в предобработке выглядит вот так: CL#1545\#37a38f89\-b3e1\-4022\-b433\-b9aeec728544:\d+:\d+:\d+:(\d+):\d+
значения макросов по-умолчанию

содержимое файла 1c_clusters_cache_1545
1c-01-win:1545#37a38f89-b3e1-4022-b433-b9aeec728544,1541,"Cloud1C";

**Comment by slothfk** [comment]
Ага, не обошлось без ошибок :( Поправлю!
