### ISSUE TITLE
Дискавери службы RAS

### ISSUE THREAD

**Issue by MegaShIzoID** [slothfk/1c_zabbix_template_ce#111]
почему-то не создается элемент данных для этого правила обнаружения в шаблоне ЦС, руками скрипт конечно же выполняется на стороне сервера. порт один - 1545

**Comment by slothfk** [comment]
Хотелось бы подробностей! Ошибки при этом или что? У меня на двух средах все работает норм вроде ...

**Comment by slothfk** [comment]
> > а можно список обнаружений показать с хоста с новым шаблоном?
> 
> ![image](https://user-images.githubusercontent.com/20921558/240536874-ad9cf7e5-588f-4403-8d7a-ee1119da1bfc.png) во, сейчас показал ошибку

В таком случае хотелось бы получить
```
$ zabbix_agentd.exe -t 1c.cs.ras.discovery[1545]
```
с проблемного сервера

**Comment by MegaShIzoID** [comment]
> В таком случае хотелось бы получить

![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/9a214423-84ff-4fbb-b917-6e8d9ad1f614)

но юзерпарам присутствует
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/126c3804-7363-4f8c-9a91-953306dd6cd6)

**Comment by slothfk** [comment]
> но юзерпарам присутствует

а сервис агента перезапускался?

**Comment by MegaShIzoID** [comment]
> > но юзерпарам присутствует
> 
> а сервис агента перезапускался?

конечно, все остальное дискаверится нормально и базы и кластер

**Comment by slothfk** [comment]
в логах агент ошибки? мне кажется это надо с агентом разбираться, что там не так ...

**Comment by MegaShIzoID** [comment]
> в логах агент ошибки? мне кажется это надо с агентом разбираться, что там не так ...

чот я затупил, для юзерпарама же линуксовая строка написана, он под виндой же ее не выполнит никак, запихал строку в отдельный скрипт, передаю просто ему параметр, буду поглядеть

**Comment by slothfk** [comment]
> > в логах агент ошибки? мне кажется это надо с агентом разбираться, что там не так ...
> 
> чот я затупил, для юзерпарама же линуксовая строка написана, он под виндой же ее не выполнит никак, запихал строку в отдельный скрипт, передаю просто ему параметр, буду поглядеть
> 
> UPD: ну да, так все заработало

Наверное, можно было без скрипта добавить в начало строки вызов `bash.exe -c`

**Comment by novel-k** [comment]
> > > в логах агент ошибки? мне кажется это надо с агентом разбираться, что там не так ...
> > 
> > 
> > чот я затупил, для юзерпарама же линуксовая строка написана, он под виндой же ее не выполнит никак, запихал строку в отдельный скрипт, передаю просто ему параметр, буду поглядеть
> > UPD: ну да, так все заработало
> 
> Наверное, можно было без скрипта добавить в начало строки вызов `bash.exe -c`

Здравствуйте.
Огромное спасибо Вам за ваши труды.
Но у меня есть вопрос.
Можете привести пример как должен выглядеть строка 
`UserParameter=1c.cs.ras.discovery[*],/usr/bin/echo "$1" | awk -F, 'BEGIN { print "{\"data\":[" } { for (i=1;i<=NF;i++) { print "{\"{#RAS_PORT}\":\""$i"\"}"(i<NF?",":"") } } END { print "]}" }'`
в файл  userparameter_1c-cs.conf для винды?
Т.е. эту строку вообще убрать и в начале файла написать
`bash.exe -c`

**Comment by MegaShIzoID** [comment]
> > > > в логах агент ошибки? мне кажется это надо с агентом разбираться, что там не так ...
> > > 
> > > 
> > > чот я затупил, для юзерпарама же линуксовая строка написана, он под виндой же ее не выполнит никак, запихал строку в отдельный скрипт, передаю просто ему параметр, буду поглядеть
> > > UPD: ну да, так все заработало
> > 
> > 
> > Наверное, можно было без скрипта добавить в начало строки вызов `bash.exe -c`
> 
> Здравствуйте. Огромное спасибо Вам за ваши труды. Но у меня есть вопрос. Можете привести пример как должна выглядеть строка: `UserParameter=1c.cs.ras.discovery[*],/usr/bin/echo "$1" | awk -F, 'BEGIN { print "{\"data\":[" } { for (i=1;i<=NF;i++) { print "{\"{#RAS_PORT}\":\""$i"\"}"(i<NF?",":"") } } END { print "]}" }'` в файл userparameter_1c-cs.conf для винды? Т.е. эту строку вообще убрать и в начале файла написать `bash.exe -c`

я прост создал файл 1c_central_ras.sh с содержимым
```
#!/bin/bash
/usr/bin/echo "$1" | awk -F, 'BEGIN { print "{\"data\":[" } { for (i=1;i<=NF;i++) { print "{\"{#RAS_PORT}\":\""$i"\"}"(i<NF?",":"") } } END { print "]}" }'
```
а в файле userparameter_1c-cs.conf заменил строку на
`UserParameter=1c.cs.ras.discovery[*],"C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent 2\zabbix_agent2.d\scripts\1c_central_ras.sh" $1`
