### ISSUE TITLE
утилиты gitforwindows.org не имеют требуемых опций

### ISSUE THREAD

**Issue by Brotherwoods** [slothfk/1c_zabbix_template_ce#113]
утилита "sort" из комплекта https://gitforwindows.org/ не имет опции "-u" которая используется в скриптах. соответственно скрипты не работают.

**Comment by slothfk** [comment]
> соответственно скрипты не работают.

Какая версия git bash? Какая ошибка при этом?

**Comment by slothfk** [comment]
![изображение](https://github.com/slothfk/1c_zabbix_template_ce/assets/16452185/015afa77-df8e-4c63-a1db-0d0ee2d7d3f9)

У меня все работает и опция `-u` на месте ...

**Comment by Brotherwoods** [comment]
проблема была в отсутствии пути к утилитам в виндовом PATH
