### ISSUE TITLE
Установка на Windows

### ISSUE THREAD

**Issue by khrykinnv** [slothfk/1c_zabbix_template_ce#114]
Добрый день!
Windows Server 2016 Standard. 1С:Предприятие 8.
Zabbix 6.4.3
Проделал следующие этапы инструкции.
1. Установил на сервер, который требуется мониторить, Git Bash
2. Поместил файл userparameter_1c-ws.conf в каталог C:\Program Files\Zabbix Agent\
3. создал папку scripts в папке с агентом и поместил туда скрипты из каталога  scripts. C:\Program Files\Zabbix Agent\scripts
4.  Внёс правки в userparameter_1c-ws.conf : "C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent\scripts\userparameter_1c-ws.conf"
5. Настроил запуск сервера RAS как службу из этой статьи: https://infostart.ru/1c/articles/810752/
6. заменил файл logcfg.xml в папке C:\Program Files\1cv8\conf. Отредактировал строки <log location="C:\1C\zabbix\problem_log" history="1">. 
7. Создал папку C:\1C\zabbix\problem_log. Журнал начал собираться. папка наполнилась
8. Выполнил импорт шаблона Template App 1C Enterprise Work Server
9. В шаблоне изменил значение макроса {$LOG_DIR} на /C/1C/zabbix/problem_log
Лог агента:
**** Enabled features ****
  5452:20230615:105351.835 IPv6 support:          YES
  5452:20230615:105351.836 TLS support:           YES
  5452:20230615:105351.837 **************************
  5452:20230615:105351.837 using configuration file: C:\Program Files\Zabbix Agent\zabbix_agentd.conf
  5452:20230615:105353.409 agent #0 started [main process]
 16092:20230615:105353.410 agent #1 started [collector]
 14712:20230615:105353.411 agent #4 started [listener #3]
  9364:20230615:105353.412 agent #3 started [listener #2]
  8604:20230615:105353.412 agent #2 started [listener #1]

Данные не отображаются. В чем может возникнуть проблема?
Спасибо.

**Comment by slothfk** [comment]
> 4\. Внёс правки в userparameter_1c-ws.conf : "C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent\scripts\userparameter_1c-ws.conf"

Тут должно быть
```
"C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent\scripts\1c_work_server.sh"
```



> 9\. В шаблоне изменил значение макроса {$LOG_DIR} на /C/1C/zabbix/problem_log

Тут должно быть `/C/1C/zabbix`, в `problem_log` сохраняются журналы в случае обнаружения каких-то проблем!



> Данные не отображаются.

О каких именно данных речь?

**Comment by khrykinnv** [comment]
Добрый день. 
Была проблема с подключением активного агента к серверу zabbix. 
Благодарю за ответ.

**Comment by khrykinnv** [comment]
Да, проблема устранена.

**Comment by Kybinskiy** [comment]
Ребята, помогите, уже устал бороться с этими ошибками по интерграции 1с + забикс.
в общем проблема такая, в забиксе сами шаблоны выдают ошибку Preprocessing failed for: /usr/bin/bash: C:\Program Files\Zabbix Agent\scripts\1c_work_server.sh: No such file or directory
1. Failed: cannot perform regular expression "ragent: \d+ (\d+) \d+" match for value of type "none": pattern does not match

сколько не гуглил не могу найти решение. права на все службы уже дал полные, админские (1с RES, 1С serv, Zabbix gent), тех журнал собирается, в макросах прописан путь правильно, bash установлен. 
по ощущения у меня как то не отрабатываю скрипты в баше, хотя он выдают и свою версию и другую инфу... 
в чём может быть проблема? 
![2024-11-14_10-41-55](https://github.com/user-attachments/assets/1370e7f5-fceb-446c-9144-755c8c4f1324)

**Comment by slothfk** [comment]
> /usr/bin/bash:

Вот это в Win надо изменить на путь к bash.exe, так как в Win нет /usr/bin/bash

**Comment by Kybinskiy** [comment]
где изменить?

**Comment by Kybinskiy** [comment]
переменные win все на месте, в .conf файлах для забикса тоже все подменено.
более чем, все файлы и настройки по web курсу настраивались, но увы что то в них не рассказали что б работало

**Comment by Kybinskiy** [comment]
> > /usr/bin/bash:
> 
> Вот это в Win надо изменить на путь к bash.exe, так как в Win нет /usr/bin/bash

можно пж поконкретнее где что поменять нужно? не совсем понимаю про что конкретно идёт речь....

**Comment by slothfk** [comment]
> можно пж поконкретнее где что поменять нужно? не совсем понимаю про что конкретно идёт речь....

полагаю это `usrparameter-1c_ws.conf`
