### ISSUE TITLE
Надо ли обязателньо запускать RAS на том же сервере где лежат лицензии физически?

### ISSUE THREAD

**Issue by Brotherwoods** [slothfk/1c_zabbix_template_ce#115]
Надо ли чтобы лицензии учитывались запускать RAS именно на сервере лицензирования? или это может быть произвольный сервер возможно без кластероа 1С вообще.. просто хост на котором крутится RAS ?

**Comment by slothfk** [comment]
Подразумевается, что **RAS** запускается на **центральном сервере** кластера!!! Мне кажется, это вполне логичное его "местожительство" ...

**Comment by Brotherwoods** [comment]
В инсталляциях с сервером лицензирования на центральном сервере как правило физических файлов лицензий нет.
Но при запуске скриптов идет проверка на наличие утилиты ring. Зачем?  если ее не будет - будут ли лицензии показываться корректно?

**Comment by Brotherwoods** [comment]
Влияет ли получение списка лицензий которое было произведено через ring на результат вывода количества лицензий обнаруженных при запросе к RAS?

**Comment by slothfk** [comment]
> Влияет ли получение списка лицензий которое было произведено через ring на результат вывода количества лицензий обнаруженных при запросе к RAS?

О каком обнаружении при запросе к ras вы толкует? Если речь про число сеансов, потребляющих лицензию с данного сервера лицензирования, то эта величина никак не зависит от наличия/отсутствия license-tools как на сервере лицензирования, так и на других серверах кластера

**Comment by Brotherwoods** [comment]
Вот смотрите,  
1. есть центральный сервер. на нем файлов лицензий нет.
2. есть сервер с утилитой RAS - которая настроена на центральный сервер. на нем файлов лицензий нет
3. есть сервер лицензирования, на котором лежат лицензии.
1c_license_server.sh - запускается на сервер 2 (там же где запущен RAS), поскольку не понимает в настройках хост, а только порт.  хуже того, скрипт почему то хочет заниматься автообнаружением запущенных процессов 1С, несмотря на то, что ему в явном виде подсунули список портов RAS.  может быть с целью мониторинга памяти процессов? в данном случае не будем вдаваться в разбор этого вопроса и для простоты можно объеденить 1 и 2 сервера - поставить RAS там же где центральный сервер. будем считать что это логично [на самом деле нет, но пусть будет].
в скрипте 1c_license_server.sh есть обращение к функции license_info которая дергает ring. которая вызывается из licenses_summary. наличие этой функции и успех вызова, никак не влияет на последующий учет утилизированных (сеансы потребляющие лицензию) лицензий?

**Comment by slothfk** [comment]
Давайте я поясню, чтобы был понятен выбранный подход, и на этом закроем данной обращение!?

Исходная концепция выглядит следующим образом:
* имеется выделенный сервер лицензирования, включаемый в **n**-ое количество кластеров
* у каждого кластера, разумеется, есть центральный сервер (а может даже не один), на котором запускается в том числе и сервис **RAS** (получаем, что на всех центральный серверах **RAS** работает на одинаковом, по-умолчанию - **1545**, порту)
* скрипту, выполняемому на сервере лицензирования, передается только номер порта **RAS** и учетные данные администратора кластера (да, они должный быть одинаковыми для всех кластеров, в которые входит данный сервер лицензирования). Далее скрипт анализирует список процессов на сервере и составляет список центральных серверов тех кластеров, к которым он (сервер лицензирования) подключен. По этому списку и происходит поключение к сервисам **RAS** для получения информации о сеансах!
* утилизация лицензий сервера лицензирования подсчитывается исходя из информации, указываемой в свойствах сеанса в "выдаче" **RAS**, **ring** при этом никак не участвует/задействован!

Надеюсь, данное пояснение добавит ясности!

**Comment by Brotherwoods** [comment]
> * скрипту, выполняемому на сервере лицензирования, 

А вот тут стоп. 

Сервер лицензирования  согласно концепции (строка выше - "... центральный сервер ... на котором .. сервис RAS") - не имеет запущенного RAS.

Тоесть сервер лицензирования отдельно, а центральный сервер - отдельно, и RAS - на центральном сервере (на самом деле он тоже отдельно должен быть, ну, будем считать что эта условность неизбежна в данном случае).
Соответственно скрипт сбора данных о лицензия - должен выполняться на центральном сервере?

Непонятно зачем:

> * передается только номер порта **RAS** 

зачем выполнять скрипт подсчета лицензий на сервере лицензирования если RAS работает на совсем другом сервере?

**Comment by slothfk** [comment]
> зачем выполнять скрипт подсчета лицензий на сервере лицензирования если RAS работает на совсем другом сервере?

Наверное для того, чтобы собирать информацию о сеансах в одном месте, агрегируя ее до того как она попадет в **zabbix**

> еще непонятно зачем вообще нужно автоматическое определение RAS - если мы в любом случае создаем эти сервисы сами? RAS по умолчанию на кластере не самоконфигурируется. Его конфигурирует администратор.

Мне кажется вы "гребете все в одну кучу" и "мягкое" и "теплое" ...

> Особенно неприятны проблемы с условностями котоыре привносит автоматическое определение когда кластеров несколько на одном хосте. ведь для каждого из них свой RAS который на своем порту.

Ну так задавайте эти порты в макросе `{$RAS_PORTS}` через запятую ...
