### ISSUE TITLE
Проблема с элементами данных + discovery

### ISSUE THREAD

**Issue by maximmikulich1** [slothfk/1c_zabbix_template_ce#116]
Всем привет ! 

Уже сломал голову где капать, может подскажите 

Добавил все конфиги и скрипты согласно инструкции, в правилах обнаружения получаю ошибки, вот пример:
![issue1](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/1ae435b7-c3ce-4057-bf69-7339caecd17c)
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/d6c1883d-18d5-46e8-894c-e914b8e02a56)

Это при тесте некоторых правил обнаружения
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/e85f3a07-427b-4c6f-aa60-f649a7093350)

И куча куча ошибок в элементах данных
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/d0831436-7a61-4db5-8bc9-15a3da428cbe)

Только осваиваюсь в мониторинге 1с через заббикс, буду благодарен за любую помощь !)

**Comment by maximmikulich1** [comment]
Для уточнения
Заббикс сервер 6.0
Windows server 2016
Учетной записи в консоли администрирования не создано

**Comment by slothfk** [comment]
> И куча куча ошибок в элементах данных
> ![image](https://user-images.githubusercontent.com/103995514/247088905-d0831436-7a61-4db5-8bc9-15a3da428cbe.png)

Тут все предельно ясно написано - "нет такого файла" ... У вас там пробел меж именем файла скрипта и праметром запуска отсутствует ...

Может быть в других случаях похожие "ошибки"!?

**Comment by maximmikulich1** [comment]
Шаблон брал ваш, инструкцией тоже пользовался вашей
Не совсем понимаю, где эти пробелы выставляются ? 
Порядка 40 элементов данных имеют эту ошибку Preprocessing failed for: /usr/bin/bash: C:\zabbix\scripts\1c_central_server.shsessions: No such file or directory именно с 1c_central_server.sh

Имеются так же ошибки формата Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "grep: -P supports only unibyte and UTF-8 locales", но на всех скриптах стоят utf-8

**Comment by slothfk** [comment]
> Не совсем понимаю, где эти пробелы выставляются ?

см. `userparameter_1c-cs.conf`

**Comment by maximmikulich1** [comment]
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/48836ea9-d912-4793-9b05-df7b5472172e)
Пробелы в норме

**Comment by slothfk** [comment]
> C:\zabbix\scripts\1c_central_server.shsessions

может были не в норме? рестарт агента заббикс сделать?

**Comment by maximmikulich1** [comment]
В норме
Заббикс агент перезапускал, на сервере кэш конфигурации чистил, все равно, в логах на сервере тоже ругается на эту же ошибку 
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/e72b4153-1e69-4e59-b4b0-849e3c9ba34f)

**Comment by slothfk** [comment]
> ![image](https://user-images.githubusercontent.com/103995514/247134325-48836ea9-d912-4793-9b05-df7b5472172e.png) Пробелы в норме

Для работы обнаружения, в последней строке, вместо `/usr/bin/echo "$1"`, необходимо написать `"C:\Program Files\Git\bin\bash.exe" -c "echo $1"`

**Comment by maximmikulich1** [comment]
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/fbe4f655-9fcf-4a79-81fd-396d79548029)
Почему элемент данных может ругаться ? В скриптах и на операционной системе проверял, стоит UTF-8. В прошлых обсуждениях не нашел рабочего решения

**Comment by slothfk** [comment]
> В прошлых обсуждениях не нашел рабочего решения

Это пока расследуем в рамках #117, понимания где "стреляет" пока нет ... У меня на вин-среде такой ошибки нет ...
Предлагаю по этому вопросу вести обсуждение в той ветке!

По исходным симптомам проблема осталась или решилась?

**Comment by maximmikulich1** [comment]
У меня просто тоже вин среда
Отличная идея, буду в #117 ждать решения

По исходным симптомам проблема решилась, проблема в большей части была на моей стороне, спасибо ! 

Я бы еще предложил сделать обсуждение по настройке этих шаблонов и скриптов для "чайников", кто мало работает с 1с и может встречаться со стандартными проблемами. Шаблон и скрипты реально крутые для глубокого анализа 1с, спасибо

**Comment by maximmikulich1** [comment]
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/fb68aa92-e88d-4cf5-ad24-ed585418afb8)
Может есть инструкция по настройке мониторинга технологического журнала ? Или это всего лишь включение тех журнала в 1с и добавление директории через макрос ? Возможно кому-то будет полезно

**Comment by slothfk** [comment]
> это всего лишь включение тех журнала в 1с и добавление директории через макрос ?

Подразумевалось что именно так:
* подложить файлик **logcfg.xml** или добавить секции из него, скорректировав каталоги
* поменять макрос
* активировать необходимые элементы данных и все должно заработать ...

**Comment by slothfk** [comment]
> По исходным симптомам проблема решилась, проблема в большей части была на моей стороне, спасибо !

В таком случае этот "инцидент" считаем исчерпанным ;)

> Я бы еще предложил сделать обсуждение по настройке этих шаблонов и скриптов для "чайников", кто мало работает с 1с и может встречаться со стандартными проблемами

Есть мысля сделать что-то типа мастер-класса для Вин-пользовтелей :)

**Comment by maximmikulich1** [comment]
> Есть мысля сделать что-то типа мастер-класса для Вин-пользовтелей :)

Это хорошая идея и было бы много кому полезным :)
