### ISSUE TITLE
Состояние процессов кластера

### ISSUE THREAD

**Issue by MegaShIzoID** [slothfk/1c_zabbix_template_ce#117]
Опять винда.
На состояние процессов пишет вот такое
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/c6325e28-e712-4b67-ae1e-260c881a76e5)
Выполненный руками кусок запроса говорит то же самое, запрос руками в баше без грепа показывает вот такое
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/bcb92954-c90f-42ef-9ff8-5545a7913f7f)

**Comment by MegaShIzoID** [comment]
Интересная загогулина, если остановить службы рагент и рас, то значения в виде ноликов - прилетают
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/3de51d5b-bede-43ee-98b8-353efb89a647)
в итоге триггер про потерю связи с кластером горит теперь перманентно

**Comment by slothfk** [comment]
В таком случае хотелось бы глянуть вывод
```
$ bash.exe -x 1c_license_server.sh proccess <cluster_uuid> rmngr <ras_port> <ras_timeout> <ras_user> <ras_pass>
```
где
`<cluster_uuid>` - идентификатор кластера, можно скорпировать из вывода команды wmic или из заббикса
`<ras_port>` - порт сервиса **ras**
`<ras_timeout>` - таймаут ожидания ответа от ras
`<ras_user>` - администратор кластера
`<ras_pass>` - пароль администратора кластера

**Comment by MegaShIzoID** [comment]
> В таком случае хотелось бы глянуть вывод
> 
> ```
> $ bash.exe -x 1c_license_server.sh proccess <cluster_uuid> rmngr <ras_port> <ras_timeout> <ras_user> <ras_pass>
> ```
> 
> где `<cluster_uuid>` - идентификатор кластера, можно скорпировать из вывода команды wmic или из заббикса `<ras_port>` - порт сервиса **ras** `<ras_timeout>` - таймаут ожидания ответа от ras `<ras_user>` - администратор кластера `<ras_pass>` - пароль администратора кластера

![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/90ac4176-33e8-46f2-a42e-0772d7e7c246)

**Comment by slothfk** [comment]
Ну и тогда в догонку прям в том же окне
```
"C:\Program Files\Git\bin\bash.exe" -c locale
```

**Comment by MegaShIzoID** [comment]
> Ну и тогда в догонку прям в том же окне
> 
> ```
> "C:\Program Files\Git\bin\bash.exe" -c locale
> ```

![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/20921558/75578730-e8e2-45d4-99be-d282ceec301e)

**Comment by slothfk** [comment]
Проблему воспроизвел, буду разбираться ...
