### ISSUE TITLE
Файл лицензии не прошел проверку 

### ISSUE THREAD

**Issue by maximmikulich1** [slothfk/1c_zabbix_template_ce#119]
Всем привет ! 

Настроил мониторинг на этом шаблоне, все работает за исключением лицензий. На сервере предприятия 1с активированы две лицензии (Серверная и пользовательская), в шаблоне есть автообнаружение этих лицензий и следовательно заббикс автоматически создает элемент данных и триггер проверки файла лицензии. Файлы лицензии обнаружились, но при попытке тест получаю "пустое значение в ответ" и следовательно срабатывание триггера. Напрямую через утилиту ring с сервера лицензии проходят валивацию без проблем. Не нашел топиков с этими вопросами, не подскажите где копать ? 
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/103995514/a2f49fc4-bb01-4f3b-b42a-379bc9f0697d)

**Comment by slothfk** [comment]
На какой платформе это все? Win или Lin?

**Comment by maximmikulich1** [comment]
Windows server 2016

**Comment by slothfk** [comment]
А license-tools (т.е. ring license) только одна версия установлена?

**Comment by maximmikulich1** [comment]
Да, ring license установлен только одной версией. Напрямую с сервера через утилиту ring всю информация о лицензиях получаю корректно

**Comment by sc0rp10n87** [comment]
При вызове метода license_check из 1c_license_files.sh всегда возвращает пустое значение.

Причина в строке
RESULT=$(${1} license validate --name "${2}" --send-statistics false 2>/dev/null) && echo "Ok" || echo "${RESULT}"

связано с тем что параметр ${1} в себе содержит путь в к утилите ring который выглядит как C:\Program Files\1C\1CE\components.......
требуется изменить строку на

RESULT=$("${1}" license validate --name "${2}" --send-statistics false 2>/dev/null) && echo "Ok" || echo "${RESULT}"

проставить знак " в перед и после переменной ${1}

В этом случае windows корректно считывает путь и запрос на валидацию лицензий выполняется корректно.
