### ISSUE TITLE
Ошибка синтаксиса в CentOS7

### ISSUE THREAD

**Issue by spawnax** [slothfk/1c_zabbix_template_ce#122]
./1c_common_module.sh: line 134: syntax error near unexpected token `('
./1c_common_module.sh: line 134: `        grep -i "^${HOSTNAME}" "${CLSTR_CACHE}_"?(${RAS_PORTS//,/|}) | sed -re 's/^([/][^:]+:)?//''

**Comment by slothfk** [comment]
Где возникает данная ошибка? При каком режиме использования?

**Comment by spawnax** [comment]
Ошибка идёт при простом вызове скрипта из bash без передачи параметров. Т.е. проверка синтаксиса не проходит конструкция из ?(${RAS_PORTS//,/|})

**Comment by slothfk** [comment]
> Ошибка идёт при простом вызове скрипта из bash без передачи параметров

Позвольте полюбопытствовать, а вы это для чего делаете?

**Comment by spawnax** [comment]
Пытаюсь заставить шаблоны работать. На текущий момент кроме статуса RAS сервера ничего не собирает.
Я так понимаю что проблема где-то в отработке скриптов, вот и решил их руками потестировать. Все скрипты отрабатывают кроме 1c_common_module, он на проверке синтаксиса вываливается.

**Comment by slothfk** [comment]
> Все скрипты отрабатывают кроме 1c_common_module, он на проверке синтаксиса вываливается.

Он и не должнен отрабатывать, так как не вызывается напрямую!

Дело вряд ли в скриптах, так как данный шаблон у нас работает на *centos7*

Учитывая то, что вы пишете, у вас агент zabbix настроен ли корректно для работы в активном режиме?

В элементах данных присутсвуют ошибки или что?

**Comment by spawnax** [comment]
ок, принял, действительно что-то не то с правами у заббикса:

[root@srv1c scripts]# sudo -u zabbix ./1c_work_server.sh memory
awk: cmd. line:18: (FILENAME=- FNR=5) fatal: can't redirect to `/tmp/1c_rphost_pid_hash' (Permission denied)

**Comment by slothfk** [comment]
Посмотрите #59 - это selinux

**Comment by slothfk** [comment]
либо вы сначала запускали скрипты от **root**, а теперь пытаетесь выполнить от **zabbix**
Проверьте владельца файла `/tmp/1c_rphost_pid_hash`

**Comment by slothfk** [comment]
Удалось ли разобраться/решить проблему?

**Comment by spawnax** [comment]
Добрый день, пока непонятно куда копать, SElinux отрубил. В логах вот такое сообщение:
 52948:20230804:125106.420 no active checks on server [192.168.4.197:10051]: host [srv1c.kit-systems.ru] not found
 52948:20230804:125106.421 cannot parse list of active checks: cannot find pair with name "commands"

**Comment by slothfk** [comment]
у вас агент не настроен корректно для работы в активном режиме ... почитайте мануал по *заббикс* на эту тему

**Comment by slothfk** [comment]
Остались ли еще какие-то вопросы или закрываем?
