### ISSUE TITLE
Не работают графики [1С/Серверные вызовы] ТОП{$TOP_LIST_SIZE} "ленивых" вызовов

### ISSUE THREAD

**Issue by andrews4646** [slothfk/1c_zabbix_template_ce#125]
Добрго времени суток!
Подскажите пожалуйста! Возможно ли включить графики [1С/Серверные вызовы] ТОП{$TOP_LIST_SIZE}?
данные с этих триггеров есть, история есть, но графики пустые, это баг или фича?
![Снимок экрана 2023-08-18 в 15 40 09](https://github.com/slothfk/1c_zabbix_template_ce/assets/18006597/71ee37b2-627e-470d-8854-bd0207a50a2b)
![Снимок экрана 2023-08-18 в 15 39 25](https://github.com/slothfk/1c_zabbix_template_ce/assets/18006597/6144b3dd-7868-4f68-b051-509d3fd07e41)

**Comment by slothfk** [comment]
У этих элементов данных нет графиков и быть не может, так как это текст!

**Comment by deniszhyravel70-byte** [comment]
<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/da436c66-eaa6-46e2-b960-055b76ce31a3" />

<img width="1643" height="312" alt="Image" src="https://github.com/user-attachments/assets/9f07707e-851e-4203-92c1-a16c1afe82bc" />

подскажите что тут не так делаю?)

**Comment by deniszhyravel70-byte** [comment]
"C:\Program Files\Git\bin\bash.exe" "C:\Program Files\Zabbix Agent 2\scripts\1c_work_server.sh" calls "/c/TechLog1C" count
прописал так пошло
