### ISSUE TITLE
Windows agent zabbix 

### ISSUE THREAD

**Issue by MaxiSTEP159** [slothfk/1c_zabbix_template_ce#126]
Проблемы с zabbix
в логах агента:
git установлен

13308:20230928:115855.018 Zabbix Agent stopped. Zabbix 6.0.22 (revision c083ca2ca4c).
  4600:20230928:115855.397 Starting Zabbix Agent [SERVERNAME]. Zabbix 6.0.22 (revision c083ca2ca4c).
  4600:20230928:115855.401 **** Enabled features ****
  4600:20230928:115855.405 IPv6 support:          YES
  4600:20230928:115855.409 TLS support:            NO
  4600:20230928:115855.412 **************************
  4600:20230928:115855.415 using configuration file: C:\zabbix\conf\zabbix_agentd.conf
  4600:20230928:115856.077 agent #0 started [main process]
  2764:20230928:115856.081 agent #1 started [collector]
10396:20230928:115856.086 agent #3 started [listener #2]
  8512:20230928:115856.089 agent #2 started [listener #1]
13620:20230928:115856.092 agent #4 started [listener #3]
10044:20230928:115856.096 agent #5 started [active checks #1]
10044:20230928:115856.198 active check "1c.cs.ib.restrictions" is not supported: Unsupported item key.
10044:20230928:115856.204 active check "1c.ls.sessions[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115856.207 active check "1c.ls.infobases.discovery[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115856.211 active check "1c.ls.clusters.discovery[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115856.214 active check "1c.ws.perfs[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115856.217 active check "1c.ws.memory" is not supported: Unsupported item key.
10044:20230928:115856.219 active check "1c.ws.ram" is not supported: Unsupported item key.
10044:20230928:115856.221 active check "1c.ws.excps[/c/zabbix/1c/log]" is not supported: Unsupported item key.
10044:20230928:115856.224 active check "1c.cs.infobases.discovery[0,1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115856.226 active check "1c.cs.sessions[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115926.246 active check "1c.ws.memory" is not supported: Unsupported item key.
10044:20230928:115956.268 active check "1c.ls.sessions[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115956.276 active check "1c.ws.perfs[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:115956.280 active check "1c.ws.memory" is not supported: Unsupported item key.
10044:20230928:115956.284 active check "1c.cs.sessions[1545,1.5,,]" is not supported: Unsupported item key.
10044:20230928:120026.308 active check "1c.ws.memory" is not supported: Unsupported item key.

C:\zabbix\1c\log 
тут три папки с логами 1с   calls excps locks - логи сыпет
сам заббикс агент установлен C:\zabbix конфиг C:\zabbix\conf
 скрипты   C:\zabbix\scripts
файлы  userparameter_1c-* поправлены согласно рекомендациям пример: "C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_license_files.sh"
(лежат они  C:\zabbix\conf и C:\zabbix\zabbix_agentd.conf.d и C:\zabbix\conf\zabbix_agentd.conf.d    не понятно куда правильно ложить )
log dir в макросе сервера указано     /c/zabbix/1c/log
hostname на агенте и вебке сервера совпадают
служба запущена из под администратора пк

подскажите пжлста что делаю не так?

**Comment by slothfk** [comment]
> (лежат они C:\zabbix\conf и C:\zabbix\zabbix_agentd.conf.d и C:\zabbix\conf\zabbix_agentd.conf.d не понятно куда правильно ложить )

Полагаю, надо не гадать, а почитать документацию к настройке агента **zabbix**, ну или заглянуть в файл конфигурации агента, отыскав там секции типа <code>Include=</code>

**Comment by MaxiSTEP159** [comment]
### Option: Include
#	You may include individual files in the configuration file.
#
# Mandatory: no
# Default:
# Include=

# Include=c:\zabbix\zabbix_agentd.userparams.conf
# Include=c:\zabbix\zabbix_agentd.conf.d\
# Include=c:\zabbix\zabbix_agentd.conf.d\*.conf


сути это не поменяло
сам служба работает с конфигом C:\zabbix\conf\zabbix_agentd

если я Вас правильно понимаю 
c:\zabbix\zabbix_agentd.conf.d\  сюда положить нужно userparameter_1c-*

ситуации это не меняет.... i need help

**Comment by MaxiSTEP159** [comment]
Include=C:\zabbix\zabbix_agentd.conf.d
если раскоментить это то служба не стартует

**Comment by slothfk** [comment]
> Include=C:\zabbix\zabbix_agentd.conf.d если раскоментить это в конфиге агента, то служба не стартует

Что в логах агента при этом?

**Comment by MaxiSTEP159** [comment]
так лог не создается , служба не стартует  ошибка 1053

**Comment by slothfk** [comment]
Проверяйте файлы userparameter на предмет ошибок, или отключите все, а потом включайте по одному и смотрите что происходит

**Comment by MaxiSTEP159** [comment]
на примере 1ой строки из файла
UserParameter=1c.cs.sessions[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_central_server.sh" sessions $1 $2 $3 $4
верный синтаксис??

**Comment by slothfk** [comment]
> на примере 1ой строки из файла UserParameter=1c.cs.sessions[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_central_server.sh" sessions $1 $2 $3 $4 верный синтаксис??

визуально вроде все ок ...

**Comment by MaxiSTEP159** [comment]
если отключаю то служба работает
поочередность подключения ничего не дает

**Comment by slothfk** [comment]
Возможно проблема в формате файла, а именно переноса строки? Глянье файл в простом блокноте, возможно там перенос строк не обрабатывается корректно?

**Comment by MaxiSTEP159** [comment]
нет с этой точки всё верно

**Comment by slothfk** [comment]
> нет с этой точки всё верно

Хм, вы пишете про ошибки на сервере лицензировния, т.е. для него конфиги работают нормальн или он у вас на линуксе?

> 1. не показывает занятые, а нам именно это нужно  - тут я предположил,  что занятые покажутся только на том где есть информационные базы не так ли?

Занятые? Это "выданные" данным сервером лицензирования. Они считаются на основе имени сервера, если у вас сервер лицезнирования, например, добавлен по ip-адресу, то подсчет работать не будет!

> 2\. с датами окончания вот такая беда:
> 
> 
> Preprocessing failed for: 20230329122451.lic:20.:не ограничен..20230329102840.lic:500.:не ограничен..20230329122133.lic:1.:...
> 
>     1. Failed: cannot perform regular expression "20230329122133.lic:\w+:(.*)" match for value of type "string": pattern does not match
>        это обходной путь решения...

Про это не понял, обходной путь для чего?

**Comment by slothfk** [comment]
> p/s изначально задача стоит по лицензиям точнее по их использованию

Давайте про это в рамках отдельного обращения

**Comment by MaxiSTEP159** [comment]
Lic1S  это линукс
на нем
1)весит на сервере шаблон [Template App 1C License Files]
2) это шаблон показывает количество лицензий, но даты в ошибке...
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/50843586/55622f72-2819-4769-94c2-a7e32c7c49e6)
3) не отображает занятые лицензии

Следовательно пытаемся на виндовом сервере  поднять забикс-агента  для мониторинга (на верхней картинке это 1s)
и не получается

**Comment by slothfk** [comment]
А зачем вы пытаетесь запустить скрипт `1c_common_module.sh`? Он для этого не предназначен!

**Comment by skymegabyte** [comment]
В попытке разобраться в чем причина остановки агента zabbix, как у автора.

**Comment by slothfk** [comment]
> как только я сейчас расскомментирую Include в основном конфиге
> у меня не стартует заббикс агент

Удалось ли разобраться? Что в журналах агента zabbix, при включенных файлах userparameter?

**Comment by OooBonooO** [comment]
> > как только я сейчас расскомментирую Include в основном конфиге
> > у меня не стартует заббикс агент
> 
> Удалось ли разобраться?

При редактировании блокнотом файлов типа userparameter_1c-*  была нарушена кодировка с  UTF-8 на UTF-8 with BOM, пересохранить файлы в UTF-8 и служба запустится
