### ISSUE TITLE
Cannot evaluate function last: item is not supported

### ISSUE THREAD

**Issue by Olex7771** [slothfk/1c_zabbix_template_ce#129]
Добрый день! Может кто подсказать вроде всё подключил в триггере пишет ошибку
Cannot evaluate function last: item is not supported

![123](https://github.com/slothfk/1c_zabbix_template_ce/assets/33567936/d30a17ea-c4d7-47f7-8e1e-ddea3894b8a3)

**Comment by slothfk** [comment]
Есть ощущение, что не настроен агент заббикс, т.е. он ничего не знает про файл userparemeter_1c-ws.conf

**Comment by slothfk** [comment]
За отсутствием обратной связи
