### ISSUE TITLE
Не отображаются данные по соединениям 1С

### ISSUE THREAD

**Issue by dumonikk** [slothfk/1c_zabbix_template_ce#130]
Добрый день!
Вводные данные:
есть сервер лицензирования на win2016 x64 и n-ое количество кластеров 1С. Хотел мониторить количество соединений, но отображается все по нулям. Обнаружение включено. Все делал по инструкции. Все скрипты и конфиги находятся на сервере лицензирования.
При выполнении скрипта 1с_license_server.sh used выдает список лицензий с нулями. В какую сторону двигаться, чтобы отображались корректные данные? второй скриншот
![1](https://github.com/slothfk/1c_zabbix_template_ce/assets/100779885/186097b8-e258-4c7f-933e-c5ce85937247)
![2](https://github.com/slothfk/1c_zabbix_template_ce/assets/100779885/732ee403-c01b-4bf3-b47d-273073981a77)

**Comment by slothfk** [comment]
Скрипт выполняется с правами администратора?
Есть ли администраторо кластера?

**Comment by dumonikk** [comment]
1) да, с правами администратора
2) администратора кластера нет

**Comment by slothfk** [comment]
ras работает?

**Comment by dumonikk** [comment]
да, запущен. Учетная запись администратора для службы
![3](https://github.com/slothfk/1c_zabbix_template_ce/assets/100779885/1a009f34-ee82-41cc-b49c-fedc90d79f13)

**Comment by slothfk** [comment]
> да, запущен. Учетная запись администратора для службы ![3](https://user-images.githubusercontent.com/100779885/280978577-1a009f34-ee82-41cc-b49c-fedc90d79f13.jpg)

Речь про **Remote Administration Server** (ras.exe)

**Comment by dumonikk** [comment]
нашел в чем допустил ошибку, сервер ras необходимо запускать на центральном сервере, куда раздается лицензия.
