### ISSUE TITLE
Нулевые значения последних данных

### ISSUE THREAD

**Issue by CoreeZz** [slothfk/1c_zabbix_template_ce#131]
Добрый день. 

Установили и настроили шаблон, автообнаружение сработало и добавились кластеры. 
Но значения нулевые при получении данных. 
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/75156159/599c866d-6c75-4b06-8851-0a4dd7a52b1b)
По сеансам также, 0 вовзращается.
![image](https://github.com/slothfk/1c_zabbix_template_ce/assets/75156159/12a2d230-a0e2-40de-9ed7-889306e3c8fb)
Zabbix 6.4.6, рас установлен и заббикс подключается.
С чем может быть связано?

**Comment by slothfk** [comment]
Где установлен ras? Есть ли администратор кластера?

**Comment by CoreeZz** [comment]
RAS установлен на сервере 1С на котором крутятся основные базы, то есть центральный. Администраторов кластеров нет, только администратор сервера. Пока не ввёл правильные учетные данные администратора сервера, кластеры не были обнаружены.

**Comment by CoreeZz** [comment]
Если нужна дополнительная информация, могу собрать, отдэбажить.

**Comment by CoreeZz** [comment]
Пока вопрос отпал. Назначил администраторов кластеров на кластеры, данные появились. Прошу прощения, не совсем внимательно увидел описание макроса.
