### ISSUE TITLE
Под windows не отдает данные по блокировкам

### ISSUE THREAD

**Issue by amelentjev** [slothfk/1c_zabbix_template_ce#138]
Установил, как написано в документации Git Bash
$ echo ${BASH_VERSION}
5.2.26(1)-release

Заметил, что метрика 1c.ws.logs отдает только lock и всё. Т.е. вывод выглядит вот так : 
$ "/c/Program Files/Zabbix Agent/Scripts/1C/_1c_work_server.sh" locks /c/Logs 20 1545
lock: 39395

Полечилось заменой строки
`    read -ar RESULT < <(cat "${LOG_DIR}"/rphost_*/"${LOG_FILE}.log" 2>/dev/null | \
`
на
`    mapfile -t RESULT < <(cat "${LOG_DIR}"/rphost_*/"${LOG_FILE}.log" 2>/dev/null | \
`

**Comment by slothfk** [comment]
Ошибка общая, мой косяк
Исправил в e27a355
