### ISSUE TITLE
Не отображается лицензия в zabbix

### ISSUE THREAD

**Issue by dumonikk** [slothfk/1c_zabbix_template_ce#139]
Добрый день!
по определенным базам не отображает данные по выданным лицензиям сервером лицензирования, как на скрине ниже. 
Windows server 2016, zabbix 6.0.25
![image](https://github.com/user-attachments/assets/ba6b514a-96a5-4d0d-b5ad-a2a4bfc61adf)

вывод used 
![image](https://github.com/user-attachments/assets/0433022e-088e-4e23-8a9a-f65578a54013)

Можете подсказать, куда копать?

**Comment by slothfk** [comment]
Сходу не готов ответить, но судя по приведенным скриншотам - данные от разных кластеров ...

**Comment by dumonikk** [comment]
сервер лицензирования находится в нескольких кластерах. В 3-х кластерах скрипт почему не отрабатывает

**Comment by slothfk** [comment]
В этих кластерах есть ли администраторы кластера, соотвествуют ли учетки той, в кластере которого скрипт отрабатывает?

**Comment by dumonikk** [comment]
администраторов нет, соот-но RAS_PASS и RAS_USER не заполняю
![image](https://github.com/user-attachments/assets/70493c54-1df4-4be6-b92d-257427ef4d5a)

**Comment by slothfk** [comment]
А как кластера собраны? Сетевые имена (DNS) работают ли или как кластера "собраны"?

**Comment by dumonikk** [comment]
не актуально
