### ISSUE TITLE
В Zabbix не отображается число выданных лицензий

### ISSUE THREAD

**Issue by orfosit** [slothfk/1c_zabbix_template_ce#142]
Доброго дня! 
Во первых огромный респект разработчикам скриптов. Была проделана титаническая работа !
Помогите пожалуйста разобраться с настройкой скриптов, вроде уже все проверил. 

Ситуация есть тестовый сервер, где  установлен кластер 1С и добавлены базы, в нем же и добавлена сущность сервера лицензирования, в разделе Рабочие сервера. Сервер лицензирования отдельная физическая машина. На основном сервер поднят RAS. Работает подключение к RAS от сервера лицензирования. Скрин
![image](https://github.com/user-attachments/assets/ebc1995d-7bc5-4b43-a7d2-412031a7c0ef)
На сервере лицензирования настроен Zabbix, включен тех.журнал по инструкции. настройки переменных в скриптах выполнены. 
Пример на скрине.
![image](https://github.com/user-attachments/assets/fffe4964-a229-4eb1-8586-1392b6a86bdf)
В мониторе Zabbix информация поступает. Видно общее количество серверных лицензий и общее количество клиентских лицензий, но не видно количество выданных лицензий. 
![image](https://github.com/user-attachments/assets/12961bec-7ee2-4ace-a320-cd997e840f23)

**Comment by slothfk** [comment]
Правильно ли я понимаю, что вы параметры `RAS_USER` и `RAS_PASS` в скриптах прописывали?

**Comment by orfosit** [comment]
> Правильно ли я понимаю, что вы параметры `RAS_USER` и `RAS_PASS` в скриптах прописывали?

Да правильно в скрипте scripts/1c_common_module.sh
в разделе 
# Параметры взаимодействия с сервисом RAS

**Comment by slothfk** [comment]
> Да правильно в скрипте scripts/1c_common_module.sh в разделе "# Параметры взаимодействия с сервисом RAS"

Так делать не надо, потому что это переопределяется значенями макросов, задаваемых в zabbix!

**Comment by orfosit** [comment]
А как надо? Где нужно указать параметры подключения к Ras серверу, логин и пароль админа кластера.

**Comment by slothfk** [comment]
![image](https://github.com/user-attachments/assets/6a7cfdba-d65b-4050-af3e-6ba11e8f6f76)

![image](https://github.com/user-attachments/assets/cd8928d4-212b-4b27-88be-dbdc8325b7c4)

https://www.zabbix.com/documentation/6.4/ru/manual/config/macros/user_macros

**Comment by orfosit** [comment]
@slothfk Большое спасибо за ответ!

**Comment by slothfk** [comment]
> @slothfk Большое спасибо за ответ!

Если вопрос закрыт, предлагаю закрыть задачку

**Comment by orfosit** [comment]
Шаблоны макросов применили, количество выданных лицензий все равно не считается. Поэтому вопрос по архитектуре. Если сервер лицензирования, это отдельный физический сервер, то где мы должны настроить Zabbix, а где настроить RAS.
Сейчас у нас на сервере лицензирования настроен Zabbix, + ТЖ . Сервер RAS поднят на основном сервере 1С. В кластере серверов на сервере лицензирования нет зарегистрированных баз и соответственно RAS не показывает ничего. На тестовом сервере RAS работает, можно посмотреть список баз. и т.д. В моем понимании мы должны указать путь до RAS, но где и как непонятно. Либо проглядял. Заранее спасибо!

**Comment by slothfk** [comment]
Для сбора данных о лицензиях компоненты шаблона устанавливаются на сервере лицензирования (физическом или виртуальном, не суть).
RAS должен быть запущен на центральном сервере кластера!
Скрипт сам определяет центральный сервер кластера, к которому подключен сервер лицензирования (делая это на основе списка процессов ОС). Далее подключается к RAS по найденному в списке процессов сетевому имени и порту, который указан в макросе `{$RAS_PORTS}`

**Comment by limbaughtv** [comment]
@slothfk 
Правильно ли Я понимаю, что ставить RAS на сервере лицензирования не нужно ? 
Я установил RAS на всех серверах и везде порт 1545 (Прод. Тест, Сервер лиценз.), данные идут , но именно по выданным лицензиям нет, вот ошибка - 

<img width="814" height="71" alt="Image" src="https://github.com/user-attachments/assets/1d27cf81-82a3-479c-9ca3-26909a1ccca9" />

<img width="650" height="31" alt="Image" src="https://github.com/user-attachments/assets/34080114-d7fb-479d-9124-d03e41a618e4" />


Так же есть ошибка на сервере лицензий - [1С/Сервер лицензирования] Нарушена связь с кластером ****]

На серв. лиц. нет кластера

**Comment by slothfk** [comment]
> Правильно ли Я понимаю, что ставить RAS на сервере лицензирования не нужно ?

"Архитектура" скриптов подразумевает, что RAS установлен на всех центральных сереверах кластера (сколько бы их ни было). На сервере лицензирования RAS не подразумевается!

Если сервер лицензирования на Win, то возможно агенту zabbix не хватает прав на получение списка процссов сервера 1С

**Comment by limbaughtv** [comment]
@slothfk 
Запустил Агент от учётки доменного админа и ошибка пропала -  [1С/Сервер лицензирования] Нарушена связь с кластером ], но проблема с показателями лицензий осталась [1С/Кластер/***] Количество выданных лицензий] - 

Preprocessing failed for: LIC#20230823133036.lic:0.LIC#20230823134320.lic:0.LIC#20230902091938.lic:0.summary:0:0:0:0:0
1. Failed: cannot perform regular expression "CL#0005d1fa\-21cb\-4f4f\-bf8b\-dfb0eea69435:(\d+):\d+:\d+:\d+:\d+" match for value of type "string": pattern does not match

Что то не так с лицензиями, что можно сделать?
