### ISSUE TITLE
Добавление параметров авторизации для RAC

### ISSUE THREAD

**Issue by slothfk** [slothfk/1c_zabbix_template_ce#16]
Добавить в шаблоны макросы задающие пользователя и пароль администратора, для работы с rac

**Comment by ckfn4czc** [comment]
[[ $# = 2 ]] && RAS_PORT=${2}
[[ $# = 3 ]] && CLSTR_AUTH="--cluster-user=${2} --cluster-pwd=${3}"
[[ $# = 4 ]] && RAS_PORT=${2} && CLSTR_AUTH="--cluster-user=${3} --cluster-pwd=${4}"
