### ISSUE TITLE
шаблон

### ISSUE THREAD

**Issue by Re14x** [slothfk/1c_zabbix_template_ce#25]
проблема с добавлением шаблона к хосту.
ошибка: Шаблон не может быть соединен с другим шаблоном несколько раз, даже через другие шаблоны.

**Comment by slothfk** [comment]
Предполагаю, что проблема с добавлением хосту шаблона "Сервера лицензирования". Если этому хосту ранее был добавлен шаблон "Рабочего сервера", то возможно возникновение такой ошибки, так как шаблон "Сервера лицензирования" наследует шаблон "Рабочего сервера"

**Comment by Re14x** [comment]
принял а как решить эту проблему?

**Comment by slothfk** [comment]
отключить шаблон рабочего сервера от хоста и подключить только шаблон сервера лицензирования

**Comment by Re14x** [comment]
тоесть добавить только лицензию и центральный?

**Comment by Re14x** [comment]
и он может полноценно работать без рабочего?

**Comment by slothfk** [comment]
да

**Comment by Re14x** [comment]
так теперь вопрос другой, вы писали что нужен zabbix_get  zabbix_sender   он не работает по zabbix_agentd   ?

**Comment by slothfk** [comment]
> и он может полноценно работать без рабочего?

сервер лицензирования включает все элементы от рабочего, так как он его потомок

**Comment by Re14x** [comment]
тоесть по сути из вашего репозитария я беру только 2 шаблона?

**Comment by slothfk** [comment]
> так теперь вопрос другой, вы писали что нужен zabbix_get zabbix_sender он не работает по zabbix_agentd ?
zabbix_sender - используется для отправки данных по количеству и составу файлов лицензий
zabbix_get - используется для инициирования процесса сохранения фалов ТЖ на других серверах кластера (если кластер 1С состоит более чем из 1 сервера)

> тоесть по сути из вашего репозитария я беру только 2 шаблона?
Нет, необходимо сделать импорт всех шаблонов.  А к хосту цеплять только сервер лицензирования и центральный.
Повторюсь, сервер лицензирования включает сбор всех данных по рабочему, поэтому все что необходимо для рабочего так же должно быть скопировано!

**Comment by Re14x** [comment]
принял
