### ISSUE TITLE
Лицензии

### ISSUE THREAD

**Issue by Re14x** [slothfk/1c_zabbix_template_ce#26]
можете подсказать почему не отображается кол-во лицензий который запрашивается 1c.ls.license.user  просто пустая строка в последних данных и соответственно в тригере ошибка:
Cannot evaluate expression: "Cannot evaluate function "server:1c.ls.license.user.last()": not enough data.".

**Comment by slothfk** [comment]
Этот элемент данных является вычисляемым от [1С/Лицензии] Сводная информация - 1c.ls.licenses
Который, в свою очередь является траппером, т.е. элементом, данные по которому заббикс-серверу передает сам узел наблюдения без запроса заббикс-сервера.
Для этого есть задание в /etc/cron.hourly, которое каждый час вызывает скрипт, передающий через zabbix_sender данные о количестве файлов лицензий и числе лицензированных сеансов

**Comment by Re14x** [comment]
так у меня отображаются все кроме 
 [1С/Лицензии] Количество лицензированных сеансов
[1С/Лицензии] Количество файлов пользовательских лицензий

**Comment by slothfk** [comment]
Все верно, эти данные обновляются один раз в час

**Comment by Re14x** [comment]
если его запустить руками то zabbix должен его увидеть?
запустил руками толку нет

**Comment by Re14x** [comment]
он присылает показания но в них нет того что надо summary:27:37:48:21:0
как раз нет 
Количество лицензированных сеансов
Количество файлов пользовательских лицензий

**Comment by slothfk** [comment]
Запустите скрипт
`/etc/zabbix/scripts/1c_license_server.sh info`
 что он выдаст?

**Comment by Re14x** [comment]
0:0

**Comment by slothfk** [comment]
Ок, тогда что выдает запуск
`/usr/bin/zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k 1c.ls.licenses -o $(/etc/zabbix/scripts/1c_license_server.sh info)`

**Comment by Re14x** [comment]
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000021"
sent: 1; skipped: 0; total: 1

**Comment by Re14x** [comment]
а если так /usr/bin/zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k 1c.ls.licenses -o $(/etc/zabbix/scripts/1c_license_server.sh used)
то
zabbix_sender [1451]: invalid parameter "summary:12:13:20:8:0"
эти 5 параметров и видит

**Comment by Re14x** [comment]
zabbix_sender [30769]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 1; total: 1; seconds spent: 0.000017"}]
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000017"
sent: 1; skipped: 0; total: 1

**Comment by slothfk** [comment]
Какое значение имеет параметр **Hostname** в настройках zabbx-agent на отслеживаемом сервере и какое имя хоста на Zabbix-сервере

**Comment by Re14x** [comment]
centos 1c

**Comment by slothfk** [comment]
> centos 1c

А конкретнее? Если можно цитату конфига и скриншот настроек хоста?

**Comment by Re14x** [comment]
![agent](https://user-images.githubusercontent.com/66055034/83227821-dd707800-a1a6-11ea-88a6-3514645fb8d6.jpg)
![host](https://user-images.githubusercontent.com/66055034/83227832-dfd2d200-a1a6-11ea-9b4c-e571400ad0b1.jpg)

**Comment by slothfk** [comment]
разница в регистре последней буквы

**Comment by Re14x** [comment]
данные пришли но все по нулям
![zero](https://user-images.githubusercontent.com/66055034/83229153-4953e000-a1a9-11ea-98d1-b5abe1b7e5e7.jpg)

**Comment by slothfk** [comment]
это говорит о том, что на сервере не найдено ни одного файла программной клиентской лицензии ...

**Comment by Re14x** [comment]
а как быть если нет файловой лицензии?

**Comment by slothfk** [comment]
> а как быть если нет файловой лицензии?

Быть с чем? Учет утилизации "железных" лицензий не подразумевался. Такой функционал не реализован!

Данные по сеансам будут собираться, а вот триггеры фиксирующие заканчивающиеся лицензии, понятное дело, работать не будут

**Comment by Re14x** [comment]
понял спасибо
