### ISSUE TITLE
Актуализировать статьи

### ISSUE THREAD

**Issue by slothfk** [slothfk/1c_zabbix_template_ce#28]
Т.к. структура шаблона претерпела изменения, необходимо провести актуализацию статей на Инфостарт!

**Comment by slothfk** [comment]
В статье по вызовам и блокировкам внесены минимально необходимые изменения (поправлены тексты и названия скриптов и конфигов)

**Comment by Kirill** [comment]
> 1c_valuemaps.xml.
В install.md написано импортировать этот шаблон, но такой файл в репозитории отсутствует.

**Comment by slothfk** [comment]
> > 1c_valuemaps.xml.
> > В install.md написано импортировать этот шаблон, но такой файл в репозитории отсутствует.

Спасибо за замечание, поправлю! Карта значений входит в файл 1c_work_sever.xml, поэтому нужды в отдельном файле нет и он был исключен из состава проекта!

**Comment by slothfk** [comment]
Статья по утилизации лицензий исправлена
