### ISSUE TITLE
1c_cs: Почему статус RAS всегда Down?

### ISSUE THREAD

**Issue by Kirill** [slothfk/1c_zabbix_template_ce#29]
Показание [1С/Центральный сервер] Статус сервиса RAS всегда Down, хотя сервис запущен. В списке портов слушает.

```
[root@web1c ~]# netstat -nl | grep 1545
tcp        0      0 0.0.0.0:1545            0.0.0.0:*               LISTEN
[root@web1c ~]# systemctl status ras
● ras.service - 1C:Enterprise Remote Administration Service
   Loaded: loaded (/etc/systemd/system/ras.service; enabled; vendor preset: disabled)
   Active: active (running) since Чт 2020-06-11 10:02:37 EET; 10h ago
 Main PID: 5455 (ras)
   CGroup: /system.slice/ras.service
           └─5455 /opt/1C/v8.3/i386/ras cluster --port=1545

июн 11 10:02:37 web1c systemd[1]: Started 1C:Enterprise Remote Administration Service.
июн 11 10:02:38 web1c ras[5455]: 1C:Enterprise 8.3 (8.3.16.1148) Remote Administration Server started...exit.
Hint: Some lines were ellipsized, use -l to show in full.
```

Как проверить что ему не хватает?

**Comment by Kirill** [comment]
Проверил с Zabbix Proxy
```
sudo -u zabbix zabbix_get -s 10.10.10.31 -k 'net.tcp.service[tcp,,1545]'
1
```

**Comment by slothfk** [comment]
Я не понял, вопрос актуален или нет?

**Comment by Kirill** [comment]
Еще как. В zabbix интерфейсе сработал триггер что сервис выключен. Но по факту он включен. Но как проверить почему он отображается в zabbix как выключенным - не знаю. Прошу прощения, я с заббиксом только на Вы, еще не все понимаю как проверить. Кое-что нахожу, проверяю. Но на этот вопрос пока не могу найти ответ.

**Comment by slothfk** [comment]
Последнее значение по этому элементу данных какое? Триггер срабатывает, если оно - 0. Надо разобраться почему так? Вы мониторите сервер 1с через заббикс прокси? Версия заббикс какая?

**Comment by Kirill** [comment]
Все версии 5.0.1 установленные из репозиториия zabbix для centos 7.
Сервер с 1С настроен на активную и на пассивную выдачу. Сервер подключен как на скриншоте. Как я понимаю, его опрашивает прокси и передает на сервер.
![image](https://user-images.githubusercontent.com/302940/84436695-2d821c80-ac34-11ea-9ae3-790dbef36e9e.png)

**Comment by Kirill** [comment]
Странно, но все оказалось гораздо проще...
Проблема была в SELinux:
По ссылке https://support.zabbix.com/browse/ZBX-14626 запустил команду ```tail /var/log/audit/audit.log | audit2why```

Получил ответ
```
type=AVC msg=audit(1595847346.211:8241): avc:  denied  { name_connect } for  pid=16030 comm="zabbix_proxy" dest=1545 scontext=system_u:system_r:zabbix_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=0

        Was caused by:
        One of the following booleans was set incorrectly.
        Description:
        Allow nis to enabled

        Allow access by executing:
        # setsebool -P nis_enabled 1
        Description:
        Allow zabbix to can network

        Allow access by executing:
        # setsebool -P zabbix_can_network 1
```

После выполнения в консоли этих двух команд все заработало:
```
setsebool -P nis_enabled 1
setsebool -P zabbix_can_network 1
```
