### ISSUE TITLE
ОШИБКА: Неверно задан каталог технологического журнала!

### ISSUE THREAD

**Issue by LetArch** [slothfk/1c_zabbix_template_ce#33]
Всё сделал по инструкции для установки. Скинул все скрипты и юзерпараметры куда нужно. Создал нужные каталоги в /var/log/1C. Сама 1Ска пишет свои логи ТЖ, а вот до заббикса они не доходят (((
Какие то данные собирает, а вот по производительности нет:
![image](https://user-images.githubusercontent.com/3818210/89171267-f7a54880-d591-11ea-97f1-19df90dbcb72.png)

**Comment by LetArch** [comment]
Даже на самом хосте где установлен сервер 1с и заббикс агент, выполняю: zabbix_agentd -t 1c.ws.rphost.count
Выдаёт: 1c.ws.rphost.count                            [m|ZBX_NOTSUPPORTED] [Unsupported item key.]

**Comment by slothfk** [comment]
> Даже на самом хосте где установлен сервер 1с и заббикс агент, выполняю: zabbix_agentd -t 1c.ws.rphost.count
> Выдаёт: 1c.ws.rphost.count [m|ZBX_NOTSUPPORTED] [Unsupported item key.]

Ну это нормально, т.к. указанный элемент данных является зависимым от элемента "Объем памяти процессов" (1c.ws.memory) и не может быт проверен подобным образом

**Comment by slothfk** [comment]
> Всё сделал по инструкции для установки. Скинул все скрипты и юзерпараметры куда нужно. Создал нужные каталоги в /var/log/1C. Сама 1Ска пишет свои логи ТЖ, а вот до заббикса они не доходят (((

Спасибо за замечание! Попробуйте пользователя **zabbix** включить в группу **grp1cv8**
