### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by DishinIR** [slothfk/1c_zabbix_template_ce#35]
Можно ли переделать под Windows или есть что-то похожее под это ОС?

**Comment by slothfk** [comment]
> Можно ли переделать под Windows

Часть функционала переделать можно легко! Вопрос, кто за это возьмется?

> или есть что-то похожее под это ОС?

Бесплатно и с подобным набором метрк - не уверен ...

**Comment by slothfk** [comment]
@DishinIR, а какой функционал для Вас наиболее актуален в первую очередь?

**Comment by slothfk** [comment]
Коллеги, следящие за проектом и страждущие решения на Win, а подскажите ка мне. как получить параметры вызова командной строки запуска процесса? Т.е., к примеру, я хочу получить параметры запуска rphost.exe (всякие -regport, -reghost). Как?
wmic отдает такую информацию только Администратору, как я понимаю, или может пользователя можно включить в какую-то группу?
