### ISSUE TITLE
1c_central_server.sh sessions

### ISSUE THREAD

**Issue by dmelnikovnfc** [slothfk/1c_zabbix_template_ce#48]
Добрый день
/etc/zabbix/scripts/1c_central_server.sh sessions
CL#867196fc-6edd-11ea-329b-9418823879c8:5:0:0:0:0:0:0:0:0:0
IB#4dda1c70-6ee6-11ea-6687-9418823879c8:5:0:0:0:0:0:0:0:0:0
summary:5:0:0:0:0:0:0:0:0:0

однако получаю вот это в состоянии 
![image](https://user-images.githubusercontent.com/67064348/101451972-118ad980-393e-11eb-907a-7e7c7088c824.png)

**Comment by dmelnikovnfc** [comment]
сорри, сам дурак, пароль логин не прописал от ras

**Comment by slothfk** [comment]
Правильно ли я понимаю, что ошибок больше нет и обращение можно закрыть?

**Comment by dmelnikovnfc** [comment]
да, спасибо
