### ISSUE TITLE
Зашитый в скрипте путь к каталогу технологического журнала

### ISSUE THREAD

**Issue by bofh2010** [slothfk/1c_zabbix_template_ce#53]
В скрипте 1c_work_server.sh при проверке каталога ТЖ указан путь обязательно содержащий папку zabbix. Это описано в установке, но иногда это не совсем удобно. 
Мне пришлось править скрипт в этой части для получения работоспособного результата.
И да. Речь идет об установке на ОС Windows.

**Comment by slothfk** [comment]
> Это описано в установке, но иногда это не совсем удобно.

Ну тут на вкус и цвет, как говорится ...
И не так важно на какой это платформе! В текущих условиях менять данный момент не планируется!
Однако, за отзыв спасибо!
