### ISSUE TITLE
Unsupported item key

### ISSUE THREAD

**Issue by az-bp** [slothfk/1c_zabbix_template_ce#55]
Импортировал шаблон в zabbix server. 
Данные по 1С с агента не передаются.
В логах zabbix агента(Windows) подобные сообщения:

active check "1c.ls.check" is not supported: Unsupported item key.
active check "1c.ws.memory" is not supported: Unsupported item key.
active check "1c.ws.perfs[1545,1.5,user123,pass123]" is not supported: Unsupported item key.
active check "1c.cs.sessions[1545,1.5,user123,pass123]" is not supported: Unsupported item key.

**Comment by slothfk** [comment]
А скрипы, bash и конфиги агента на сервер, за которым наблюдаете?

**Comment by az-bp** [comment]
Решил проблему, по невнимательности редактировал копию файла zabbix_agentd.conf вместо рабочего файла.

Возник другой вопрос.
Данные по Рабочему серверу передаются. По Центральному серверу - нет.
Нужны ли для этого какие-то дополнительные настройки? 
Значения для макросов {$RAS_USER}, {$RAS_PASS} в zabbix я прописал.
Я правильно понимаю, что RAS_USER - пользователь от которого запускается служба ras, во всех 3 шаблонах должен быть указан один и тот же логин/пароль?
Что нужно прописывать в параметрах {$RC_BASE_URL},{$RC_USER},{$RC_PASS}?

**Comment by slothfk** [comment]
> RAS_USER - пользователь от которого запускается служба ras

Нет - это пользователь "Администратор кластера", в описании макросов это отражено! Если одному хосту (серверу за которым осуществляется наблюдение) назначаются сразу несколько шаблонов (центральный, рабочий, лицензирования), то нет возможности указать разное значение этого макроса для разных шаблонов (оно будет едино для всех)!

> Что нужно прописывать в параметрах {$RC_BASE_URL},{$RC_USER},{$RC_PASS}?

Пока ничего. Этот функционал пока не реализован и попал в шаблон по ошибке :/
