### ISSUE TITLE
Путь к файлам для версии платформы 8.3.18 и выше на Linux

### ISSUE THREAD

**Issue by Kirill** [slothfk/1c_zabbix_template_ce#60]
Необходимо обновить правило определения пути к файлам для версии платформы 8.3.18 и выше на OS Linux.
Например для 8.3.18.1208 вот такой путь:
**/opt/1cv8/x86_64/8.3.18.1208/**

**Comment by slothfk** [comment]
Да, я в курсе смены пути, надо подумать как это универсализировать
