### ISSUE TITLE
Мониторинг блокировки регламентных заданий

### ISSUE THREAD

**Issue by sirbusby** [slothfk/1c_zabbix_template_ce#63]
Необходимо мониторить факт отсутствия блокировки регламентных заданий.

- Соответствующий элемент данных
- Триггер (с макросом, для возможности переопределения значения). По-умолчанию предлагаю сделать 1h.

**Comment by slothfk** [comment]
Есть два варианта получить необходимые данные:
* Через ras/rac
* Из файла реестра кластера
Однако каждый вариант имеет свои "сложности":
* Для ras/rac необходимы учетные данные пользователя - администратора инфобазы, то есть zabbix-серверу необходимо знать администраторов всех ИБ в кластере
* Для реестра кластера, необходимо знать его местоположение и пользователь ОС zabbix, от которого работает агент, должен иметь права чтения данного файла

Второй вариант выглядит предпочтительнее, но вопрос в автоматическом определении его местоположения, либо указания его через макрос ...

**Comment by sirbusby** [comment]
Согласен про второй вариант, иногда люди отвечающие за мониторинг не имеют доступа к базам.

**Comment by slothfk** [comment]
>     * пользователь ОС zabbix, от которого работает агент, должен иметь права чтения данного файла

Если с Win сценарием (по-умолчанию) в это плане все просто, там агент от имени системы работает, то в Lin сценарии придется давать права, по-видимому через **sudo**

**Comment by denibal** [comment]
Для меня тема тоже актуальна, надеюсь на скорою проработку и включение в последующие релизы.

**Comment by slothfk** [comment]
> Для меня тема тоже актуальна, надеюсь на скорою проработку и включение в последующие релизы.

На Lin или Win?

**Comment by denibal** [comment]
> > Для меня тема тоже актуальна, надеюсь на скорою проработку и включение в последующие релизы.
> 
> На Lin или Win?

Win (но в будущем и Lin будет нужен)

**Comment by sirbusby** [comment]
> 
> 
> > Для меня тема тоже актуальна, надеюсь на скорою проработку и включение в последующие релизы.
> 
> На Lin или Win?



> 
> 
> > Для меня тема тоже актуальна, надеюсь на скорою проработку и включение в последующие релизы.
> 
> На Lin или Win?

Для меня пока на Windows, но потом будет актуально и для Linux.

**Comment by nastasyabva** [comment]
Для меня тема тоже актуальна, надеюсь на скорою проработку и включение в последующие релизы.

**Comment by slothfk** [comment]
Коллеги, какая периодичность опроса состояния блокировки будет оптимальной, на ваш взгляд?
5 минут годится?

**Comment by sirbusby** [comment]
Да, нормально.

**Comment by nastasyabva** [comment]
> Коллеги, какая периодичность опроса состояния блокировки будет оптимальной, на ваш взгляд?
> 5 минут годится?

Да

**Comment by nastasyabva** [comment]
> > Для меня тема тоже актуальна, надеюсь на скорою проработку и включение в последующие релизы.
> 
> На Lin или Win?

Lin

**Comment by slothfk** [comment]
Коллеги, буду признателен за обратную связь, все ли работает? На Вин, на Лин ...
