### ISSUE TITLE
Превышен порог длительности пользовательского вызова

### ISSUE THREAD

**Issue by mas-adm** [slothfk/1c_zabbix_template_ce#65]
Добрый день!
Возможно ли ли в тригере Превышен порог длительности пользовательского вызова сделать определение пользователя | ПК? Для оперативного определения длинных запросов.

**Comment by slothfk** [comment]
Подскажите, каков дальнейший сценарий использования данной информации (т.е. какие действия будут предприняты, когда будет известно, скажем, имя "проблемного" пользователя)?
Нужен ли номер сеанса? Может быть инструмент для завершения данного сеанса прям из **zabbix**?

**Comment by mas-adm** [comment]
Хотелось бы выяснить что вызывает такой такой долгий запрос. Узнав кто его запускает, можно к примеру выявить кривую обработку или отчет и отдать программистам на анализ. Завершать в ручную из zabbix конечно очень удобно (не нужно будет выискивать в консоле его). На данный момент уже 1д 11ч 58м выполняется. Не пытаюсь завершить, пока не пойму как определять кто и что запустил.

**Comment by slothfk** [comment]
> На данный момент уже 1д 11ч 58м выполняется. Не пытаюсь завершить, пока не пойму как определять кто и что запустил.

Так в консоли кластера видно же сеансы с активным вызовом!? Т.е. в данном случае я не понял в чем сложность определить "негодяя"?

**Comment by mas-adm** [comment]
Проблема в том что негодяя нет (в данном случае он в другой смене) и его пк выключен, а судя по zabbix что-то выполняется. Как мне понять что? Я точно знаю кто и где запустил, но что не знаю. Даже анализ тж в Инструментарии разработчика не показывает таких длительных запросов.

**Comment by mas-adm** [comment]
[https://drive.google.com/file/d/1PRDUV2JHegzLmOCXavQrmnQleeZbzEOe/view?usp=sharing](url)
Вот мой журнал

**Comment by mas-adm** [comment]
Было бы очень круто в zabbix увидеть кто и что запустил

**Comment by slothfk** [comment]
> https://drive.google.com/file/d/1PRDUV2JHegzLmOCXavQrmnQleeZbzEOe/view?usp=sharing
> Вот мой журнал

Данные файлы ТЖ, к сожалению бесполезны в решении вашей задачи.
Информация о вызове не попадет в ТЖ до момента его (вызова) завершения! Посему, полагаю, что единственным местом, в котором можно что-то почерпнуть, является ЖР, в котором можно отобрать по пользователю события на период времени соответсвующий началу данного длительного вызова. Ну и текущие операции данного пользователя посмотреть ...
У нас наблюдаются длительные пользовательские вызовы, которые продолжают выполнятся, не смотря на закрытый клиент, при работе с базой через веб-публикацию. Помогает только принудительное завершение такового!

**Comment by slothfk** [comment]
Закрыта по ошибке, неправильно указал номер в коммите

**Comment by slothfk** [comment]
Добавлен элемент данных "Сеанс длительного пользовательского вызова", содержащий информацию о имени пользователя и номере сеанса, который имеет самую большую текущую длительность вызова.
Элемент данных относится к обнаружению информационных баз, таким образом работает только в этом разрезе
Смысла делать аналогичный элемент данных в разрезе кластеров, как и в целом по серверу пока не вижу!

**Comment by mas-adm** [comment]
> Добавлен элемент данных "Сеанс длительного пользовательского вызова", содержащий информацию о имени пользователя и номере сеанса, который имеет самую большую текущую длительность вызова.
> Элемент данных относится к обнаружению информационных баз, таким образом работает только в этом разрезе
> Смысла делать аналогичный элемент данных в разрезе кластеров, как и в целом по серверу пока не вижу!

Добрый день! Я обновил все скрипты и шаблоны, но по прежнему не могу увидеть сеанс. Элемент "Сеанс длительного пользовательского вызова" есть, но никаких данных по нему нет.
--


<br class="Apple-interchange-newline">

**Comment by slothfk** [comment]
> Элемент "Сеанс длительного пользовательского вызова" есть, но никаких данных по нему нет.

Косяк увидел, поправлю!
