### ISSUE TITLE
Проблемы с мониторингом

### ISSUE THREAD

**Issue by tiresias0din** [slothfk/1c_zabbix_template_ce#68]
Здравствуйте, помогите пожалуйста разобраться.
Делаю всё по инструкции, 1С установлен под windows server 2016
Bash поставлен.
Ras в качестве системной службы на сервере запущен.
Что сделал не так? Где ошибся? 
Практически никакие показатели не снимаются по шаблонам. Показывает только что RAS запущен, а кластер нет (но кластер и не нужен). Версия забикса 5.0.12
Из файлов userparameter перемещены строчки в zabbix_agentd.win.conf (пробовал и отдельно в папку забикс файлы кидать и пути изменять)

UserParameter=1c.cs.ib.availability[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_central_server.sh" ib_status $1
UserParameter=1c.cs.sessions[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_central_server.sh" sessions $1 $2 $3 $4
UserParameter=1c.cs.ib.restrictions[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_central_server.sh" ib_restrict

UserParameter=1c.cs.clusters.discovery[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_central_server.sh" clusters
UserParameter=1c.cs.infobases.discovery[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_central_server.sh" infobases $1 $2 $3 $4 $5

UserParameter=1c.ls.sessions[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_license_server.sh" used $1 $2 $3 $4
UserParameter=1c.ls.check[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_license_server.sh" check

UserParameter=1c.ls.clusters.discovery[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_license_server.sh" clusters

UserParameter=1c.ws.locks[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_work_server.sh" locks $1 $2 $3 $4 $5 $6
UserParameter=1c.ws.calls[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_work_server.sh" calls $1 $2 $3
UserParameter=1c.ws.memory[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_work_server.sh" memory
UserParameter=1c.ws.ram[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_work_server.sh" ram
UserParameter=1c.ws.excps[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_work_server.sh" excps $1
UserParameter=1c.ws.dump_logs[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_work_server.sh" dump_logs $1 $2
UserParameter=1c.ws.perfs[*],"C:\Program Files\Git\bin\bash.exe" "C:\zabbix\scripts\1c_work_server.sh" perfomance $1 $2 $3 $4
logcfg.xml 

В логах забикса выдает следующие ошибки

 "1clic:1c.cs.clusters.discovery" became not supported: Invalid discovery rule value:
 51572:20210621:132429.762 discovery rule "1clic:1c.cs.infobases.discovery[{$IBNAME_WITH_CLSTR},{$RAS_PORT},{$RAS_TIMEOUT},{$RAS_USER},{$RAS_PASS}]" became not supported: Invalid discovery rule value:
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.hsd" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:\d+:\d+:\d+:\d+:\d+:\d+:(\d+)" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.hb" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:(\d+):\d+:\d+" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.cld" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:\d+:\d+:\d+:(\d+)" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.bgd" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:\d+:\d+:\d+:\d+:(\d+)" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.bg" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:(\d+):\d+:\d+:\d+" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.as" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:\d+:\d+:(\d+):\d+" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.http" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:\d+:(\d+)" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.wsd" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:\d+:\d+:\d+:\d+:\d+:(\d+)" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.ws" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:(\d+):\d+" match for value of type "string": pattern does not match
 51543:20210621:132429.961 item "1clic:1c.cs.sessions.total" became not supported: Preprocessing failed for:
1. Failed: cannot perform regular expression "summary:(\d+):\d+:\d+:\d+:\d+" match for value of type "string": pattern does not match

**Comment by tiresias0din** [comment]
В общим практически никакие показатели не снимаются по шаблонам. Показывает только что RAS запущен а кластер нет (но кластер и не нужен). Версия забикса 5.0.12

**Comment by slothfk** [comment]
https://github.com/slothfk/1c_zabbix_template_ce/blob/master/docs/install.md#%D0%BE%D0%B1%D1%89%D0%B8%D0%B5-%D0%B7%D0%B0%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F
Замечание про **ServerActive** и **Hostname** выполнено?

**Comment by tiresias0din** [comment]
Активные проверки у меня работают на других узлах. 
Hostname совпадает

**Comment by tiresias0din** [comment]
Вот попробовал снова отдельно в папке файлы расположить, выдало ошибку в логах на сервере

 54885:20210621:143323.408 discovery rule "1clic:1c.cs.infobases.discovery[{$IBNAME_WITH_CLSTR},{$RAS_PORT},{$RAS_TIMEOUT},{$RAS_USER},{$RAS_PASS}]" became not supported: Unsupported item key.
 54857:20210621:143323.466 item "1clic:1c.cs.ib.restrictions" became not supported: Unsupported item key.
 54857:20210621:143323.467 item "1clic:1c.cs.sessions[{$RAS_PORT},{$RAS_TIMEOUT},{$RAS_USER},{$RAS_PASS}]" became not supported: Unsupported item key.
 54857:20210621:143323.467 item "1clic:1c.ls.check" became not supported: Unsupported item key.
 54857:20210621:143323.467 item "1clic:1c.ls.sessions[{$RAS_PORT},{$RAS_TIMEOUT},{$RAS_USER},{$RAS_PASS}]" became not supported: Unsupported item key.
 
 такую ошибки выдал агент   
   5152:20210621:144053.616 active check "1c.cs.infobases.discovery[0,1545,1.5,,]" is not supported: Unsupported item key.
  5152:20210621:144557.907 active check "1c.cs.ib.restrictions" is not supported: Unsupported item key.
  5152:20210621:144557.908 active check "1c.cs.sessions[1545,1.5,,]" is not supported: Unsupported item key.
  5152:20210621:144557.908 active check "1c.ls.check" is not supported: Unsupported item key.
  5152:20210621:144557.909 active check "1c.ls.sessions[1545,1.5,,]" is not supported: Unsupported item key.

**Comment by slothfk** [comment]
Совершенно очевидно, что zabbix-агент ничего не знает про такие элементы данных ...
что говорит команда
<pre>zabbix_agentd.exe -c <файл_настроек_агента> -t 1c.cs.infobases.discovery[0,1545,1.5,,]</pre>
на сервере, который пытаемся мониторить?

**Comment by tiresias0din** [comment]
C:\zabbix>zabbix_agentd.exe -c zabbix_agentd.win.conf -t 1c.cs.infobases.discovery[0,1545,1.5,,]
zabbix_agentd.exe [18696]: Warning: EnableRemoteCommands parameter is deprecated, use AllowKey=system.run[*] or DenyKey=system.run[*] instead
1c.cs.infobases.discovery[0,1545,1.5,,]       [t|╨Ю╨и╨Ш╨С╨Ъ╨Р: ╨Э╨╡ ╨╜╨░╨╣╨┤╨╡╨╜ ╤Д╨░╨╣╨╗ ╤Б╨┐╨╕╤Б╨║╨░ ╨║╨╗╨░╤Б╤В╨╡╤А╨╛╨▓!
{"data":[  ]}]

**Comment by slothfk** [comment]
Администратор кластера задан?

**Comment by tiresias0din** [comment]
Администратор кластера не задан. Требуется?
Агент забикса? Служба запущена как системная, под учеткой админа все делается.

**Comment by tiresias0din** [comment]
Спасибо, кажется всё получилось.

**Comment by slothfk** [comment]
> Спасибо, кажется всё получилось.

Где "стреляло"?

**Comment by tiresias0din** [comment]
Я подошел к вопросу комплексно. После ошибки EnableRemoteCommands полез в config забикса и пересобрал его заного, снова поставил службу RAS и т.д. После этого всё заработало. Где-то я точно был невнимателен. 
Можно пожалуйста попросить еще помочь

На нескольких серверах, у нас больше 10 баз, и у меня не получается разобраться, как можно исключить из сбора в забикс ненужные базы (хотелось бы с помощью макросов). Попробовал сначала графики удалить, понятно, что он их снова добавил, отключал данные сбора в элементах данных, рисует их всё равно (но пустыми). 

Так-же возник вопрос по ошибке - "ОШИБКА: Неверно задан каталог технологического журнала!"
Не собирает несколько элементов, например "[1С/Блокировки] Сводка" или всё, что связанно с "ТОП-25"

Путь до каталогов, который я указывал - C:\zabbix\log (там 1С начал создавать папку calls, файлы и т.д.
В самом забиксе в поле макроса {$LOG_DIR} вписал /c/zabbix/log

**Comment by slothfk** [comment]
> Путь до каталогов, который я указывал - C:\zabbix\log (там 1С начал создавать папку calls, файлы и т.д.
> В самом забиксе в поле макроса {$LOG_DIR} вписал /c/zabbix/log

Для этого необходимо, чтобы в указанном каталоге был вложенный каталог zabbix, а уже в нем calls, locks и др. (см. доку)
> Так же необходимо создать каталог для файлов технологического журнала (по-умолчанию /var/log/1C), в котором должен быть создан каталог zabbix с вложенным каталогом problem_log. Таким образом, в рабочей системе структура каталогов и права на них выглядят следующим образом

**Comment by slothfk** [comment]
> После ошибки EnableRemoteCommands

Хотелось бы понять обстоятельства возникновения данной ошибки. Данный шаблон не должен проводить к ней!

**Comment by slothfk** [comment]
> как можно исключить из сбора в забикс ненужные базы

Такой функционал не предусмотрен

**Comment by tiresias0din** [comment]
Начиная с Zabbix 5.0.2 параметр агента EnableRemoteCommands:
    признан устаревшим для Zabbix агента
    не поддерживается для Zabbix агента 2
используйте вместо него AllowKey = system.run[*] или DenyKey = system.run[*]
# Внутренний псевдоним для параметров AllowKey / DenyKey в зависимости от значения:
# 0 - DenyKey=system.run[*]
# 1 - AllowKey=system.run[*]

**Comment by slothfk** [comment]
> Начиная с Zabbix 5.0.2 параметр агента EnableRemoteCommands:
> признан устаревшим для Zabbix агента
> не поддерживается для Zabbix агента 2

Не очень понял, какое отношение это имеет к данному шаблону? Он не требует выполнения удаленных команд от сервера. Я так понимаю, что данный функционал вам необходим в рамках других задач?

**Comment by tiresias0din** [comment]
Это я только озвучил ошибку касательно EnableRemoteCommands
А по шаблону, думаю что ошибки сыпались от неправильно указанного порта/пути к службе ras, я когда в первый раз ставил, не учел что агентов и клиентов там несколько.

**Comment by tiresias0din** [comment]
Я все равно что-то не так понял
"Для этого необходимо, чтобы в указанном каталоге был вложенный каталог zabbix, а уже в нем calls, locks и др. (см. доку)"

Поменял сейчас в пути на сервере 1С в logcfg - на C:\zabbix
Там у меня клиент и всё остальное, создал в ней папку problem_log, также автоматом создались другие
В макросе указал /c/zabbix/
Ошибка осталась

**Comment by slothfk** [comment]
> Я все равно что-то не так понял

У вас каталог c:\zabbix\log, он указан в макросе как /c/zabbix/log, чтобы ошибки не было, в нем должны быть каталоги
c:\zabbix\log\zabbix\calls, c:\zabbix\log\zabbix\locks c:\zabbix\log\problem_log

**Comment by tiresias0din** [comment]
Спасибо большое, теперь всё заработало

**Comment by slothfk** [comment]
Тему закрываем?

**Comment by tiresias0din** [comment]
Да, спасибо еще раз. В остальном постараюсь сам разобраться.

**Comment by Usov-github** [comment]
Здравствуйте, получаю ошибку Preprocessing failed for: /usr/bin/bash: C:\Program Files\Zabbix Agent\scripts\1c_central_server.sh: No such file or directory
1. Failed: cannot perform regular expression "summary:\d+:\d+:\d+:\d+:(\d+)" match for value of type "none": pattern does not match
