### ISSUE TITLE
Мониторинг нескольких агентов на сервере

### ISSUE THREAD

**Issue by ivan-bg** [slothfk/1c_zabbix_template_ce#72]
Добрый день, необходима возможность мониторинга лицензий при работе нескольких агентов на одном сервере.
Агенты работают на разных портах.

**Comment by slothfk** [comment]
Какие именно метрики вы хотите собирать с разных агентов? Информацию о сеансах?

**Comment by ivan-bg** [comment]
Да. Надо собрать с информацию по количеству используемых лицензий. 
По умолчанию порт 1545. А у нас дополнительно, на том же сервере, используются порты  2545, 3545, 4545 и т.д.. В результате в мониторинге мы видим информацию только по тому агенту, по которому прописан порт.

**Comment by slothfk** [comment]
> Добрый день, необходима возможность мониторинга лицензий при работе нескольких агентов на одном сервере.
> Агенты работают на разных портах.

Правильно ли я понимаю, что речь идет именно про ragent? Или все же про ras, который запускается на сервере лицензирования для разных кластеров?

**Comment by ivan-bg** [comment]
Добрый день,

Да про Ragent.


С уважением,
Сушко Иван Викторович
Руководитель отдела обслуживания и развития систем

**Comment by AntonShtefo** [comment]
Было бы не плохо иметь возможность указывать SRV1CV8_DATA в макросах, так как бывает на сервере 2 кластера разных версий, и по умолчанию скрипт не работает, приходится отключать определение каталогов в common_module, и указывать каталог вручную в скрипте.
![image](https://user-images.githubusercontent.com/108125100/176381340-c12b8eec-415a-4ddc-b04f-572a88296d84.png)

**Comment by slothfk** [comment]
> Было бы не плохо иметь возможность указывать SRV1CV8_DATA в макросах, так как бывает на сервере 2 кластера разных версий, и по умолчанию скрипт не работает, приходится отключать определение каталогов в common_module, и указывать каталог вручную в скрипте. ![image](https://user-images.githubusercontent.com/108125100/176381340-c12b8eec-415a-4ddc-b04f-572a88296d84.png)

Я же правильно понимаю, что это в контексте информации по блокировкам информационных баз (регламентные задания и начала сеансов)?

**Comment by AntonShtefo** [comment]
> > Было бы не плохо иметь возможность указывать SRV1CV8_DATA в макросах, так как бывает на сервере 2 кластера разных версий, и по умолчанию скрипт не работает, приходится отключать определение каталогов в common_module, и указывать каталог вручную в скрипте. ![image](https://user-images.githubusercontent.com/108125100/176381340-c12b8eec-415a-4ddc-b04f-572a88296d84.png)
> 
> Я же правильно понимаю, что это в контексте информации по блокировкам информационных баз (регламентные задания и начала сеансов)?



> > Было бы не плохо иметь возможность указывать SRV1CV8_DATA в макросах, так как бывает на сервере 2 кластера разных версий, и по умолчанию скрипт не работает, приходится отключать определение каталогов в common_module, и указывать каталог вручную в скрипте. ![image](https://user-images.githubusercontent.com/108125100/176381340-c12b8eec-415a-4ddc-b04f-572a88296d84.png)
> 
> Я же правильно понимаю, что это в контексте информации по блокировкам информационных баз (регламентные задания и начала сеансов)?

все верно, это ошибка именно по не рабочим блокировкам в базах, так как базу скрипт ищет не в на том агенте.
