### ISSUE TITLE
1с_ls: Не отображает выданные лицензии

### ISSUE THREAD

**Issue by kaplunaleks** [slothfk/1c_zabbix_template_ce#74]
Использую файлы из **Master**
![image](https://user-images.githubusercontent.com/17850298/133777060-f01ec61d-88c7-4ff4-adc9-49def2c76533.png)

Данные по количеству лицензий есть, а данные по выданным нет.
У меня сервер только раздает лицензии и кластера на нем нет. Я так понимаю что где-то нужно добавить сервера на которых работают пользователи.

**Comment by slothfk** [comment]
На центральных серверах кластеров запущен **ras**?

**Comment by kaplunaleks** [comment]
> На центральных серверах кластеров запущен **ras**?

Нет, на них тоже нужно? Нужно будет потом дополнительно настраивать RAS на сервере лицензирования что бы он видел всех остальных?

**Comment by slothfk** [comment]
> > На центральных серверах кластеров запущен **ras**?
> 
> Нет, на них тоже нужно? Нужно будет потом дополнительно настраивать RAS на сервере лицензирования что бы он видел всех остальных?

RAS нужен только на центральных серверах кластеров, на сервере лицезнирования, если он выделенный, RAS не нужен!

**Comment by slothfk** [comment]
@kaplunaleks, как успехи?

**Comment by kaplunaleks** [comment]
> @kaplunaleks, как успехи?

Сервер лицензирования у меня стоит отдельно, я на нем выключил RAS на одном из центральных серверов включил. Насколько я понимаю сейчас нужно где-то указать адреса RAS центральных серверов но я не знаю где.

**Comment by slothfk** [comment]
> Насколько я понимаю сейчас нужно где-то указать адреса RAS центральных серверов но я не знаю где.

нет, не нужно ... 

нужно в макросе задать администратора кластера и пароль, если он используется ({$RAS_USER} и {$RAS_PASS} соответственно). Администратор должен быть одинаковым для всех центральных серверов подключенных к серверу лицензирования

**Comment by kaplunaleks** [comment]
> > Насколько я понимаю сейчас нужно где-то указать адреса RAS центральных серверов но я не знаю где.
> 
> нет, не нужно ...
> 
> нужно в макросе задать администратора кластера и пароль, если он используется ({$RAS_USER} и {$RAS_PASS} соответственно). Администратор должен быть одинаковым для всех центральных серверов подключенных к серверу лицензирования

![image](https://user-images.githubusercontent.com/17850298/134378965-76cd3b06-6506-46df-ab9a-6310397eb632.png)

А как система узнает что сервер лицензирования что-то выдал и кому он это выдал? Сейчас показатели не изменились, хотя на одном из центральных серверов запущен RAS и на нем нет администратора.

**Comment by slothfk** [comment]
> А как система узнает что сервер лицензирования что-то выдал и кому он это выдал?

It's a magic! Шутка! ;)

Скрипт на сервере лицензирования получает список процессов сервера 1с, из которого делает выводы к каким кластерам он подулючен (получая имена центральных серверов). После чего пытается подключиться к рас на всех центральных серверах, которые нашел. Если указаны макросы администратора кластера, то подключение к рас выполняется с этими учетными данными.
В какое количество кластеров включен сервер лицензирования? Менялся ли макрос {$RAS_TIMEOUT}?

Можно на сервере лицензирования запустить и прислать вывод
`bash -x 1c_license_server.sh sessions`

**Comment by kaplunaleks** [comment]
> Можно на сервере лицензирования запустить и прислать вывод
> `bash -x 1c_license_server.sh sessions`

![image](https://user-images.githubusercontent.com/17850298/134467598-6329c4cf-3356-4db1-8f36-50b33ace3a83.png)
Выдает ошибку

**Comment by slothfk** [comment]
тьфу ... sessions это у центрального ...
`bash -x 1c_license_server.sh used`

**Comment by kaplunaleks** [comment]
> bash -x 1c_license_server.sh used

![image](https://user-images.githubusercontent.com/17850298/134483522-ce183fe2-a83d-47c8-b1fb-9cccb2c76463.png)

**Comment by slothfk** [comment]
от этого же пользователя ОС тогда
`wmic path win32_process where "caption like 'rphost$'" get CommandLine`

**Comment by kaplunaleks** [comment]
> от этого же пользователя ОС тогда
> `wmic path win32_process where "caption like 'rphost$'" get CommandLine`

![image](https://user-images.githubusercontent.com/17850298/134497581-d63a600a-c0d8-4fc8-a333-adccb12356d2.png)

**Comment by slothfk** [comment]
у пользователя какие права (нужны административные, такие чтобы можно было получить списко процессов других пользователей)? от имени какого пользователя запускается агент заббикс? какая винда?

**Comment by kaplunaleks** [comment]
> у пользователя какие права (нужны административные, такие чтобы можно было получить списко процессов других пользователей)? от имени какого пользователя запускается агент заббикс? какая винда?

Windows Server 2016 Standart
Сейчас я запускал от имени администратора
![image](https://user-images.githubusercontent.com/17850298/134502012-3f0c5902-981e-434a-9ef4-b1b261304f99.png)

Zabbix Agent работает с системной учеткой
![image](https://user-images.githubusercontent.com/17850298/134502150-ebfabdba-1392-4d4d-bec2-c2977e999648.png)

**Comment by slothfk** [comment]
только заметил, после слова **rphost** в команде должен быть символ **%** ... моя опечатка, прошу прощения
`wmic path win32_process where "caption like 'rphost%'" get CommandLine`

**Comment by slothfk** [comment]
Что выдает команда
`if [ -z 1 ]; then pgrep -ax rphost; else wmic path win32_process where "caption like 'rphost%'" get CommandLine | grep rphost; fi |         sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/' | sort -u`

**Comment by kaplunaleks** [comment]
> Что выдает команда
> `if [ -z 1 ]; then pgrep -ax rphost; else wmic path win32_process where "caption like 'rphost%'" get CommandLine | grep rphost; fi | sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/' | sort -u`

![image](https://user-images.githubusercontent.com/17850298/134695866-2063ef5a-d56b-48e4-92c5-088003d14655.png)

**Comment by slothfk** [comment]
очень странно ... а сейчас?
`bash -x 1c_license_server.sh used`

и покажите что у вас в 168 строке файл **1c_common_module.sh**?

**Comment by kaplunaleks** [comment]
> очень странно ... а сейчас?
> `bash -x 1c_license_server.sh used`

![image](https://user-images.githubusercontent.com/17850298/134759665-8f9f6d40-6e05-44fa-baba-6d49090fa9d3.png)



> и покажите что у вас в 168 строке файла **1c_common_module.sh**?
![image](https://user-images.githubusercontent.com/17850298/134759711-b3828f03-c62b-45ad-b277-f1b6aec34247.png)

**Comment by slothfk** [comment]
А что после exit на первом скриншоте? Теперь вижу что скрипт получил список процессов. Каков вывод скрипта после этого?

**Comment by slothfk** [comment]
Исходя из последних строк вывода `bash -x ..` есть основания предполагать, что рас недоступен на всех центральных серверах, в кластера которых входит сервер лицензирования.
Точнее не так, скрипт не может получить с RAS этих центральных серверов информацию о кластерах. По этой причине формируется пустой файл "кэша кластеров", ну а поскольку он пустой, то не у кого "спросить" информацию о сеансах!

Разбирайтесь с доступностью RAS центральных серверов с сервера лицензирования!

**Comment by kaplunaleks** [comment]
> Разбирайтесь с доступностью RAS центральных серверов с сервера лицензирования!

Можете подсказать как проверить?

**Comment by slothfk** [comment]
> Можете подсказать как проверить?

Вызовите с сервера лицензировнаия
`rac.exe cluster list <имя сервера, на котором запущен RAS>`

**Comment by kaplunaleks** [comment]
> > Можете подсказать как проверить?
> 
> Вызовите с сервера лицензировнаия
> `rac.exe cluster list <имя сервера, на котором запущен RAS>`

Спасибо, получилось. Проблема была в неправильном пути RAS, он смотрел на старую платформу.

**Comment by slothfk** [comment]
> Спасибо, получилось.

Закрываем?

**Comment by kaplunaleks** [comment]
> > Спасибо, получилось.
> 
> Закрываем?

Да, еще раз спасибо
