### ISSUE TITLE
Странная работа мониторинга сеансов

### ISSUE THREAD

**Issue by axel36rus** [slothfk/1c_zabbix_template_ce#79]
Добрый день. 
С недавнего момента, отображение количества сеансов стало работать странно. Появились непонятные скачки на графиках. В момент когда на графике идет падение, при выполнении команды bash -x 1c_license_server.sh used на выходе мы получаем 0.
Через 5-10 минут все возвращается в норму.

$ bash -x 1c_license_server.sh used
++ dirname 1c_license_server.sh
++ sed -r 's/\\/\//g; s/^(.{1}):/\/\1/'
+ export WORK_DIR=.
+ WORK_DIR=.
+ source ./1c_common_module.sh
+ case ${1} in
+ shift
+ make_ras_params
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export RAS_PORT RAS_TIMEOUT RAS_AUTH
+ used_license
+ MAX_THREADS=0
+ check_clusters_cache
+ RMNGR_LIST=($( if [ -z ${IS_WINDOWS} ]; then pgrep -ax rphost; else
        wmic path win32_process where "caption like 'rphost%'" get CommandLine | grep rphost; fi |
        sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/' | sort -u |
        awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }' ))
++ '[' -z 1 ']'
++ sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/'
++ wmic path win32_process where 'caption like '\''rphost%'\''' get CommandLine
++ sort -u
++ grep rphost
++ awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }'
+ [[ -e /tmp/1c_clusters_cache ]]
+ [[ '' == \l\o\s\t ]]
++ grep -vc '^$' /tmp/1c_clusters_cache
+ [[ 0 -ne 0 ]]
++ date -r /tmp/1c_clusters_cache +%s
++ date -d 'last hour' +%s
+ [[ 1639032391 -lt 1639028949 ]]
+ awk -F: 'BEGIN {ul=0; as=0; cl=0; uu=0; wc=0} \
            { print $0; ul+=$2; uu+=$3; as+=$4; cl+=$5; wc+=$6; } \
            END { print "summary:"ul":"uu":"as":"cl":"wc }'
++ pop_clusters_list
++ [[ ! -f /tmp/1c_clusters_cache ]]
+ sed 's/<sp>/ /g'
++ [[ -n '' ]]
++ cat /tmp/1c_clusters_cache
++ sed 's/ /<sp>/g; s/"//g'
+ execute_tasks get_license_counts
+ [[ 1 -le 1 ]]
+ exit
summary:0:0:0:0:0

![image](https://user-images.githubusercontent.com/93194628/145348222-00f1fba2-d114-4317-b01f-3918a73201c4.png)

**Comment by axel36rus** [comment]
UPD: Если выполнить на рабочем сервере команду rac session list --licenses --cluster="id кластера" то на выходе мы получаем данные о выданных лицензиях

**Comment by axel36rus** [comment]
UPD2: Прошло 2 часа и все как ни в чем не бывало работает
bash -x 1c_license_server.sh used
++ dirname 1c_license_server.sh
++ sed -r 's/\\/\//g; s/^(.{1}):/\/\1/'
+ export WORK_DIR=.
+ WORK_DIR=.
+ source ./1c_common_module.sh
+ case ${1} in
+ shift
+ make_ras_params
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export RAS_PORT RAS_TIMEOUT RAS_AUTH
+ used_license
+ MAX_THREADS=0
+ check_clusters_cache
+ RMNGR_LIST=($( if [ -z ${IS_WINDOWS} ]; then pgrep -ax rphost; else
        wmic path win32_process where "caption like 'rphost%'" get CommandLine | grep rphost; fi |
        sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/' | sort -u |
        awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }' ))
++ '[' -z 1 ']'
++ sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/'
++ wmic path win32_process where 'caption like '\''rphost%'\''' get CommandLine
++ sort -u
++ grep rphost
++ awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }'
+ [[ -e /tmp/1c_clusters_cache ]]
+ [[ '' == \l\o\s\t ]]
++ grep -vc '^$' /tmp/1c_clusters_cache
+ [[ 2 -ne 0 ]]
+ push_clusters_list 'sql10:2541|3541' SQL10:1541
+ cat /dev/null
+ execute_tasks push_clusters_uuid 'sql10:2541|3541' SQL10:1541
+ [[ 3 -le 1 ]]
+ TASK_CMD=push_clusters_uuid
+ shift
+ export -f push_clusters_uuid
+ echo 'sql10:2541|3541' SQL10:1541
+ xargs '-d ' -P0 -i bash -c 'push_clusters_uuid ${@}' _ '{}'
+ awk -F: 'BEGIN {ul=0; as=0; cl=0; uu=0; wc=0} \
            { print $0; ul+=$2; uu+=$3; as+=$4; cl+=$5; wc+=$6; } \
            END { print "summary:"ul":"uu":"as":"cl":"wc }'
++ pop_clusters_list
++ [[ ! -f /tmp/1c_clusters_cache ]]
+ sed 's/<sp>/ /g'
++ [[ -n '' ]]
++ cat /tmp/1c_clusters_cache
++ sed 's/ /<sp>/g; s/"//g'
+ execute_tasks get_license_counts 'SQL10:49fb42c6-dd6b-4198-b44e-c909ed353d84,1541,Локальный<sp>кластер;' 'sql10:5e038c81-1cc3-4e9f-8d90-8af8e14fe836,3541,Develop<sp>(3541);588fad57-b593-4875-ac8e-d313ec0a0d73,2541,GilevRU<sp>(2541);'
+ [[ 3 -le 1 ]]
+ TASK_CMD=get_license_counts
+ shift
+ export -f get_license_counts
+ echo 'SQL10:49fb42c6-dd6b-4198-b44e-c909ed353d84,1541,Локальный<sp>кластер;' 'sql10:5e038c81-1cc3-4e9f-8d90-8af8e14fe836,3541,Develop<sp>(3541);588fad57-b593-4875-ac8e-d313ec0a0d73,2541,GilevRU<sp>(2541);'
+ xargs '-d ' -P0 -i bash -c 'get_license_counts ${@}' _ '{}'
CL#5e038c81-1cc3-4e9f-8d90-8af8e14fe836:0:0:0:0:0
CL#49fb42c6-dd6b-4198-b44e-c909ed353d84:0:389:416:0:0
CL#588fad57-b593-4875-ac8e-d313ec0a0d73:0:0:0:0:0
summary:0:389:416:0:0

**Comment by slothfk** [comment]
А можно, когда скрипт возвращает 0-и, выполнить time rac session list, каково будет время выполнения?

**Comment by axel36rus** [comment]
Наконец поймал момент.
 time ./rac.exe session list --cluster 49fb42c6-dd6b-4198-b44e-c909ed353d84
Ошибка операции администрирования
Нет ответа от сервера server_addr=tcp://SQL10:1541 timeout=60000 line=2325 file=src\DataExchangeTcpClientImpl.cpp

real    2m0.160s
user    0m0.000s
sys     0m0.015s

**Comment by axel36rus** [comment]
Перезапуск службы почему то не помогает. Не могу уловить связь когда нет ответа от службы RAS.

**Comment by slothfk** [comment]
> Перезапуск службы почему то не помогает. Не могу уловить связь когда нет ответа от службы RAS.

так тут не RAS не отвечает, а кластер 1С

**Comment by axel36rus** [comment]
странно, в этот момент никаких проблем с 1С не возникает

**Comment by slothfk** [comment]
> сервера server_addr=tcp://SQL10:1541

настораживает вот это ... 1541 - порт **rmngr** же

**Comment by axel36rus** [comment]
А какой порт должен быть?

**Comment by slothfk** [comment]
> А какой порт должен быть?

у кого? я думаю, тут не в портах дело ... а все же в том, какой именно сервис не отвечает ...

**Comment by axel36rus** [comment]
в момент возникновения проблем, можно где то увидеть какой именно сервис не отвечает?

**Comment by slothfk** [comment]
> в момент возникновения проблем, можно где то увидеть какой именно сервис не отвечает?

По-моему тут все предельно ясно написано
> Нет ответа от сервера server_addr=tcp://SQL10:1541 timeout=60000 line=2325 file=src\DataExchangeTcpClientImpl.cpp

нет ответа от `tcp://sql10:1541`

суть в том, что судя по выводу `time` для получения данной ошибки потребовалось почти 2 секунды! По-умолчанию, скрипты используют таймаут в 1.5 секунды (можно задавать в макросе `{$RAS_TIMEOUT}`). Но сути дела это не изменит, так как `rac` вернет ошибку вместо необходимых значений и на выходе скрипта все равно будут нули!

**Comment by slothfk** [comment]
Есть ли еще вопросы в рамках данного обращения?

**Comment by axel36rus** [comment]
Больше нет
