### ISSUE TITLE
Текущие сеансы

### ISSUE THREAD

**Issue by haleevra** [slothfk/1c_zabbix_template_ce#84]
Все данные по 0 логи пустые, куда копать?

**Comment by slothfk** [comment]
Хотелось бы подробностей. На какой платформе? Есть ли ошибки в zabbix? 0-е значения в каких метриках?

**Comment by haleevra** [comment]
$ bash 1c_central_server.sh sessions 1545 1.5
summary:0:0:0:0:0:0:0:0:0:0

**Comment by slothfk** [comment]
Администратор кластера есть?

**Comment by slothfk** [comment]
> $ bash 1c_central_server.sh sessions 1545 1.5
> summary:0:0:0:0:0:0:0:0:0:0

А это от пользователя с админскими правами делалось?

**Comment by geozavl** [comment]
Добрый день!

Та же самая проблема - по метрикам [1С/Сеансы] данные не поступают. 
Платформа Ubuntu 20.04, zabbix 6.2, остальные данные приходят, (даже "неполучение" общего количества лицензий удалось забороть mawk --> gawk)

В /tmp/1c_infobase_cache - пусто.

В /tmp/1c_clusters_cache:
AAA.BB.235.161:66fb4542-853d-4f45-bb70-778f2a6d5d38,1541,"Tempoline";

**Comment by slothfk** [comment]
> Был бы рад возможности диагносировать проблему.

Вопросы те же ... Администратор кластера есть?

**Comment by geozavl** [comment]
Да, пароль подставляю. Не уверен, правда, что корректно вызываю скрипт для отладки:
/var/lib/zabbix/scripts/1c_central_server.sh sessions InfoBaseName#66fb4542-aaaa-bbbb-bb70-778f2a6d5d38 1545 5 clusteradmin clusterpassword
summary:0:0:0:0:0:0:0:0:0:0

**Comment by slothfk** [comment]
Должно быть так
```
$ /var/lib/zabbix/scripts/1c_central_server.sh sessions 1545 5 clusteradmin clusterpassword
```

**Comment by geozavl** [comment]
Да, и так тоже пробовал.
summary:0:0:0:0:0:0:0:0:0:0

**Comment by geozavl** [comment]
Отладку сам разобрать не смог. 
Так что отправил: bash -x /var/lib/zabbix/scripts/1c_central_server.sh sessions 1545 5 CL-ADMIN CL-PASSWD 2>session.log

**Comment by slothfk** [comment]
ну тогда уж и 1c_clusters_cache до кучи :)

**Comment by geozavl** [comment]
Да, вы правильно поняли. Там IP. 
Простите, за прямой как валенок вопрос: в какую сторону копать, чтобы в поле появился hostname/localhost? Это же временный файл, не подлежащий правке.

**Comment by geozavl** [comment]
В общем понятно, что это поле берётся из 1c_license_server.sh check , куда, в свою очередь, попадает из привязки к IP (или к  FQDN) rphost:
 pgrep -ax rphost | sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/'|awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } else { clstr_list[$1]=clstr_list[$1]"|"$2 } } END { for ( i in clstr_list ) { print i":"clstr_list[i]} }'

Осталось понять, как аккуратно подсунуть тут FQDN вместо IP (снаружи доменное имя НЕ разрешается в IP, локально - настройки, естественно, есть).

**Comment by geozavl** [comment]
Костылик помог, всё заработало. Большое вам спасибо за наводку!

**Comment by slothfk** [comment]
> попадает из привязки к IP (или к FQDN)

Там не FQDN используется, а то, что указано при инициализации кластера (укажете полное имя, будет - FQDN, укажете "короткое" - будет короткое)

Корни этой "проблемы" растут из того, что кластер "собран" по ip-адресу, а не по сетевому имени

Правильным решением является, либо настройка DNS, либо прописывание соответсвующего имени в файле hosts

**Comment by skorovoda** [comment]
Добрый день
подскажите, такая же проблема с виндой
Подскажите куда копануть?

**Comment by slothfk** [comment]
> Добрый день подскажите, такая же проблема с виндой Подскажите куда копануть?

У вас тоже кластер по ip-адресу собран, а не по имени?

**Comment by skorovoda** [comment]
не совсем понимаю. кластер собирался на винде по стандарту. указано имя Локальный кластер, все на одном сервере лежит. Так же сегодня обнаружил странность (но это уже следующий вопрос) журналы создались почемуто в в рабочем каталоге 1с а не там где я указал в переменных

на кластере админа нет
![image](https://user-images.githubusercontent.com/70511273/188083851-3ed892a8-a1de-460c-a0a9-b64a6c009c5c.png)
![image](https://user-images.githubusercontent.com/70511273/188083939-acd567db-5608-4a8c-9a9b-30f61637d3be.png)

**Comment by slothfk** [comment]
> Так же сегодня обнаружил странность (но это уже следующий вопрос) журналы создались почемуто в в рабочем каталоге 1с а не там где я указал в переменных

О каких переменных речь? Учитывая название каталога, предположу, что в файлике logcfg.xml ничего не менялось (тот что в репозитории предназначен для установки через **ansible**)

**Comment by slothfk** [comment]
> не совсем понимаю. кластер собирался на винде по стандарту. указано имя Локальный кластер, все на одном сервере лежит.

приведите вывод из git bash команды
```
$ hostname
```

**Comment by skorovoda** [comment]
речь о макросах в самом забиксе. файл взял из конфига из репозитория

**Comment by skorovoda** [comment]
> 

$ hostname
PEB-SI-01-DBS

**Comment by slothfk** [comment]
> речь о макросах в самом забиксе. файл взял из конфига из репозитория

макрос в заббике только указывается заббикс агенту "откуда взять логи", не более ... он не меняет конфиг 1С, это надо сделать самому ....

**Comment by skorovoda** [comment]
ок, с этим разобрались, я поправлю. Спасибо
а вот с сеансами даже не знаю в какую строну начать копать

**Comment by slothfk** [comment]
> $ hostname PEB-SI-01-DBS

в таком случае хотелось бы файлик session.log получить на почту для анализа, который должен получиться после выполенния команды
```
$ bash -x 1c_central_server.sh sessions 1545 1.5 2>session.log
```

**Comment by slothfk** [comment]
и заббикс-агент от системной учтетки запущен?

**Comment by skorovoda** [comment]
> bash -x 1c_central_server.sh sessions 1545 1.5 2>session.log

да

**Comment by skorovoda** [comment]
> и заббикс-агент от системной учтетки запущен?

да

**Comment by slothfk** [comment]
За длительным отсутствием автора закрою!
