### ISSUE TITLE
Некорректный подсчет имеющихся лицензий.

### ISSUE THREAD

**Issue by valentusys** [slothfk/1c_zabbix_template_ce#85]
Добрый день!
у нас имеется 4 лицензии: 2x100 и 2x500.
Скрипт 1c_license_server.sh info определяет их как 2x100 и 2x1000

Я пытался разобраться как работает парсинг - пока не смог.

**Comment by slothfk** [comment]
Лицензии КОРП или ПРОФ?

**Comment by valentusys** [comment]
> > 2x500.
> 
> это не 1000-ая лицензия случайно?

Да, это 1000, разбитая на 2 по 500
Лицензии КОРП
