### ISSUE TITLE
Удвоение показателей

### ISSUE THREAD

**Issue by valentusys** [slothfk/1c_zabbix_template_ce#86]
Здравствуйте и спасибо вам за вашу работу.
У нас все данные касательно текущих показателей(кол-во сеансов, выданных лицензий, лицензий на клиенте) отображается х2 от факта.

Предположительно из-за двух центральных серверов кластера.
Существует ли способ получать эти данные корректно?
(сейчас обошли просто делением на 2, на стороне zabbix - но это не совсем корректно)

Лицензии КОРП

Спасибо

**Comment by slothfk** [comment]
Два центральных с уровнем отказоустойчивости >0?

**Comment by valentusys** [comment]
Да, уровень отказоустойчивости - 1

**Comment by slothfk** [comment]
На сколько я знаю, там действительно двойной набор сеансов должен быть!?
Но сам не тестировал, попробую посмотреть!

**Comment by sfaqer** [comment]
> На сколько я знаю, там действительно двойной набор сеансов должен быть!? Но сам не тестировал, попробую посмотреть!

Да, именно так, каждый клиент порождает 2 идентичных сеанса (ну с т.з консоли администрирования\RAS они одинаковые, но поидее это 2 сеанса по 1ому на каждый центральный сервер для переключения при отвале одного из)

**Comment by slothfk** [comment]
> Да, именно так, каждый клиент порождает 2 идентичных сеанса (ну с т.з консоли администрирования\RAS они одинаковые, но поидее это 2 сеанса по 1ому на каждый центральный сервер для переключения при отвале одного из)

Ну то что они "одинаковые" - это не отменяет двойной утилизации лицензий!? В противном случае сеанс бы не попадал в "выдачу" **RAS** с информацией об утилизированных лицензиях ...

**Comment by sfaqer** [comment]
> Ну то что они "одинаковые" - это не отменяет двойной утилизации лицензий!? В противном случае сеанс бы не попадал в "выдачу" **RAS** с информацией об утилизированных лицензиях ...

Отменяет, сеанса 2, но фактически потребляется только 1 лицензия, т.е одному клиенту нужна только 1 лицензия даже если там уровень отказоустойчивости 15.
В ином случае у нас сервер лиценизрования как-то утилизировал 2 тысячи лицензий, хотя их всего 1200 =)

**Comment by slothfk** [comment]
Хм, тогда это либо баг и у "неактивного" сеанса не должно быть информации о используемой лицензии, либо ...
Надо будет получить разъяснение в 1С :)
В целом посыл понял, поковыряю на досуге

**Comment by slothfk** [comment]
![изображение](https://user-images.githubusercontent.com/16452185/166945359-7bffa091-3328-4835-9639-0909dd0e6cec.png)

**Comment by slothfk** [comment]
![изображение](https://user-images.githubusercontent.com/16452185/166945467-d248d40a-e4a5-4a68-880e-5debe39defa3.png)
Необходимо "склеивать" сеансы по номеру сеанса!

**Comment by sfaqer** [comment]
> Необходимо "склеивать" сеансы по номеру сеанса!

Да, похоже на то, сейчас проверил, все такие "дубли" от уровня отказоустойчивости имеют одинаковые номера сеансов

**Comment by slothfk** [comment]
> > Необходимо "склеивать" сеансы по номеру сеанса!
> 
> Да, похоже на то, сейчас проверил, все такие "дубли" от уровня отказоустойчивости имеют одинаковые номера сеансов

А могли бы вы у себя посмотреть на сервере лицензирования сколько процессов rmngr от этого кластера (только от одного ЦС или от обоих)?

**Comment by sfaqer** [comment]
> А могли бы вы у себя посмотреть на сервере лицензирования сколько процессов rmngr от этого кластера (только от одного ЦС или от обоих)?

Только от одного, насколько я вижу процессы множатся по принципу 1 менеджер = 1 кластер, если сервер лицензирования включён в 2 кластера то и процесса два

**Comment by slothfk** [comment]
> Только от одного,

Понял спасибо!

> если сервер лицензирования включён в 2 кластера то и процесса два

ну это логично ...

**Comment by slothfk** [comment]
Пока просто размышления: нет понимания как "скрестить" вывод `rac session list` и `rac session list --licenses`, так как номер сеанса, по которому будет происходить "склеивание" (группировка), можно выцепить только из первого, а информация о лицезниях только из второго
Таким образом необходимо из первого выбрать номера сеансов, и идентификаторы сеансов `session-id`, по которыму уже сопоставлять со списком сеансов с лицензиями
Лишний запрос к `rac` увеличивает время выполнения операции, что при общей "нерасторопности" связки `rac/ras` несколько напрягает ...

**Comment by valentusys** [comment]
К сожалению, только сейчас добрались до обновления - ничего не изменилось)

**Comment by slothfk** [comment]
> К сожалению, только сейчас добрались до обновления - ничего не изменилось)

С тех пор был целиком переписан код получения сеансов, вероятно этот момент выпал из поля зрения :(

Постараюсь разобраться

**Comment by slothfk** [comment]
Попробуйте теперь, должно быть корректно ...

**Comment by valentusys** [comment]
Круто, все работает.
Спасибо!

**Comment by slothfk** [comment]
Внесенные изменения приводят к лишнему "выводу", причины пока не установлены!

Необходимо поправить!

**Comment by slothfk** [comment]
> Внесенные изменения приводят к лишнему "выводу", причины пока не установлены!
Более того приводит к неработоспособности показателей по информационным базам!

**Comment by slothfk** [comment]
@valentusys, проверьте новое исправление, все ли корректно?
