### ISSUE TITLE
Разное поведение "Включена блокировка регламентных заданий" для рабочих и тестовых баз

### ISSUE THREAD

**Issue by veshus** [slothfk/1c_zabbix_template_ce#87]
Хорошо бы иметь возможность различного поведения триггера "Включена блокировка регламентных заданий" для рабочих и тестовых баз
Для рабочих баз Алерт "Включена блокировка регламентных заданий" = Истина, для тестовых баз "Включена блокировка регламентных заданий" = Ложь

**Comment by slothfk** [comment]
Непонятно:
1. Что мешает отключить "ненужные" триггеры у тестовых баз в текущих условиях?
2. Каким образом определить какая база тестовая, а какая рабочая?

**Comment by veshus** [comment]
1. нужно не отключить триггер а инвертировать, это важно, так как работающие фоновые задания в тестовых базах (при копировании из рабочих) ведут к проблемам
2. Список рабочих баз ограничен и известен заранее, которые не рабочие - тестовые. Список тестовых баз - неошраничен, разворачиваются по требованию отдела разработок регулярно (и, ожидаемо, находятся дискавери)

**Comment by slothfk** [comment]
> 1. нужно не отключить триггер а инвертировать, это важно, так как работающие фоновые задания в тестовых базах (при копировании из рабочих) ведут к проблемам

Теперь я понял смысл :) Однако держать тестовые базы в продуктивной среде - ЗЛО!

> 2\. Список рабочих баз ограничен и известен заранее, которые не рабочие - тестовые. Список тестовых баз - неошраничен, разворачиваются по требованию отдела разработок регулярно (и, ожидаемо, находятся дискавери)

Дело в том, что список баз получается автоматически с помощью обследования, как рулить триггерами: какой для рабочей, какой для тестовой? Т.е. нужно чтобы у ИБ было два триггера и пользователь в зависимости от назначения базы включал нужный?
У меня пока нет понимания/видения как это можно решить ...
Можно попробовать сделать так, что один триггер по-умолчанию включен, другой отключен (например, блокировки включен, а отсутствия блокировки - отключен, ну или наоборот), а дальше пользователь сам меняет активность тригерров на базах?
Но мне кажется, вы это можете сделать сами под свою среду, не уверен, что это нужно в большой массе!?

**Comment by veshus** [comment]
У нас разделены рабочие и тестовые базы (как правило), но мониторить тестовые надо, как раз для понимания того, что выключены регламенты
Может быть можно предусмотреть макрос со списком продуктивных баз, типа если не в списке - инвертировать значение триггера.

**Comment by veshus** [comment]
Как вариант можно попробовать

**Comment by slothfk** [comment]
> Как вариант можно попробовать

Попробуйте, потом расскажите ;)

**Comment by slothfk** [comment]
> Как вариант можно попробовать

Таки попробовалось ли чего?

**Comment by veshus** [comment]
Пока не хватило таланта настроить триггер

**Comment by slothfk** [comment]
> Пока не хватило таланта настроить триггер

См. https://disk.yandex.ru/i/EEKEpHvjTtxdFg

**Comment by slothfk** [comment]
> См. https://disk.yandex.ru/i/EEKEpHvjTtxdFg
> 
> Склонировать триггер, сделать его деактивированным по-умолчанию, или наоборот, его оставить активированным, а деактивированным по-умолчанию сделать триггер про "Включена блокировка", тогда при добавлении новых тестовых баз будет как раз то, что требуется. Триггер у узлов появится только после того как очередной раз отработает обнаружение!


Сделал такое на одном из наших проектов, выглядит как рабочий вариант, одно необходимость "добавлять" это как "основной" функционал шаблона вызывает сомнение. ИМХО, весьма частный сценарий!
