### ISSUE TITLE
Отсутствует подсчёт количества выданных софтовых лицензий в 1c.ls.license.used (ul = 0).

### ISSUE THREAD

**Issue by geozavl** [slothfk/1c_zabbix_template_ce#89]
Добрый день!

Огромное спасибо вам за ваши волшебные скрипты!

Уточните, пожалуйста сабж - это бага, фича или ошибка конфигурации? В реальности выдаётся 20+ софтовых лицензий.

bash -x /var/lib/zabbix/scripts/1c_license_server.sh used 1545 10 clusteradmin clusterpwd > licdebug 2>&1

++ dirname /var/lib/zabbix/scripts/1c_license_server.sh
++ sed -r 's/\\/\//g; s/^(.{1}):/\/\1/'
+ export WORK_DIR=/var/lib/zabbix/scripts
+ WORK_DIR=/var/lib/zabbix/scripts
+ source /var/lib/zabbix/scripts/1c_common_module.sh
+ case ${1} in
+ shift
+ make_ras_params 1545 10 clusteradmin clusterpwd
+ [[ -n 1545 ]]
+ RAS_PORT=1545
+ [[ -n 10 ]]
+ RAS_TIMEOUT=10
+ [[ -n clusteradmin ]]
+ RAS_AUTH=--cluster-user=clusteradmin
+ [[ -n clusterpwd ]]
+ RAS_AUTH+=' --cluster-pwd=clusterpwd'
+ export RAS_PORT RAS_TIMEOUT RAS_AUTH
+ used_license
+ MAX_THREADS=0
+ check_clusters_cache
+ RMNGR_LIST=($( if [ -z ${IS_WINDOWS} ]; then pgrep -ax rphost; else
        wmic path win32_process where "caption like 'rphost%'" get CommandLine | grep rphost; fi |
        sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/printf "$(host \1|cut -f 5 -d \" \")":/e' | sort -u |
        awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }' ))
++ '[' -z ']'
++ sort -u
++ pgrep -ax rphost
++ sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/printf "$(host \1|cut -f 5 -d \" \")":/e'
++ awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }'
+ [[ -e /tmp/1c_clusters_cache ]]
+ [[ '' == \l\o\s\t ]]
++ grep -vc '^$' /tmp/1c_clusters_cache
+ [[ 1 -ne 1 ]]
++ date -r /tmp/1c_clusters_cache +%s
++ date -d 'last hour' +%s
+ [[ 1662968863 -lt 1662967676 ]]
+ awk -F: 'BEGIN {ul=0; as=0; cl=0; uu=0; wc=0} \
            { print $0; ul+=$2; uu+=$3; as+=$4; cl+=$5; wc+=$6; } \
            END { print "summary:"ul":"uu":"as":"cl":"wc }'
+ sed 's/<sp>/ /g'
++ pop_clusters_list
++ [[ ! -f /tmp/1c_clusters_cache ]]
++ [[ -n '' ]]
++ cat /tmp/1c_clusters_cache
++ sed 's/ /<sp>/g; s/"//g'
+ execute_tasks get_license_counts 'p597892.domain.ru.:0983303d-0d35-xxxx-xxxx-f900202b6423,1541,cluster_name;'
+ [[ 2 -le 1 ]]
+ TASK_CMD=get_license_counts
+ shift
+ export -f get_license_counts
+ xargs '-d ' -P0 -I task_args bash -c 'get_license_counts ${@}' _ task_args
+ echo 'p597892.domain.ru.:0983303d-xxxx-xxxx-9451-f900202b6423,1541,cluster_name;'
CL#0983303d-0d35-xxxx-xxxx-f900202b6423:0:43:52:20:0
summary:0:43:52:20:0

Заранее спасибо за обратную связь!

**Comment by slothfk** [comment]
Полагаю, корни проблемы те же что и в #84 использование ip-адреса при инициализации кластера 1С
Так как скрипт определяет по сетевому имени сервера с него ли выдана лицензия или нет ...
Так как в рамках #84 у вас была коррекция скриптов, то возможно что-то пошло не так, как должно

**Comment by geozavl** [comment]
Понял, спасибо. так оно и есть. Конечно же, тут в выводе /opt/1C/v8.3/x86_64/rac session list --licenses   -     ip-адрес, который не бьётся в скриптах с "подкостыленным" доменным именем в /tmp/1c_clusters_cache.

Спасибо.
