### ISSUE TITLE
ras не всегда выдаёт данные по лицензиям

### ISSUE THREAD

**Issue by IlyaSapytskiy** [slothfk/1c_zabbix_template_ce#90]
Добрый день.
Стоял и работал сервер с платформами от 8.3.17 до 8.3.21 не последние. Пришлось перейти на 8.3.21.1484 и началось непонятное - в рандомные периоды времени под нагрузкой 1c.ls.sessions может выдать нули. При этом через минуту всё хорошо и выдаёт реальное значение.
Такое проявляется не только у меня, но и у "соседей" тоже.
Выглядит это так:
нормальный вопрос/ответ
`6564:20220921:123734.680 execute_str() command:'"C:\Program Files\Git\bin\bash.exe" "C:\Progs\zabbix_agent\scripts\1c_license_server.sh" used 1545 1.5  ' len:75 cmd_result:'CL#65ba5bcc-b679-465'
  6564:20220921:123734.681 for key [1c.ls.sessions[1545,1.5,,]] received value [CL#65ba5bcc-b679-4656-8a2e-5e28b08d889d:16:62:71:55:0
summary:16:62:71:55:0]
  6564:20220921:123734.681 In process_value() key:'1c-test:1c.ls.sessions[{$RAS_PORT},{$RAS_TIMEOUT},{$RAS_USER},{$RAS_PASS}]' lastlogsize:null value:'CL#65ba5bcc-b679-4656-8a2e-5e28b08d889d:16:62:71:55:0
summary:16:62:71:55:0'`
плохой вопрос/ответ
`6564:20220921:123836.665 execute_str() command:'"C:\Program Files\Git\bin\bash.exe" "C:\Progs\zabbix_agent\scripts\1c_license_server.sh" used 1545 1.5  ' len:67 cmd_result:'CL#65ba5bcc-b679-465'
  6564:20220921:123836.665 for key [1c.ls.sessions[1545,1.5,,]] received value [CL#65ba5bcc-b679-4656-8a2e-5e28b08d889d:0:0:0:0:0
summary:0:0:0:0:0]
  6564:20220921:123836.666 In process_value() key:'1c-test:1c.ls.sessions[{$RAS_PORT},{$RAS_TIMEOUT},{$RAS_USER},{$RAS_PASS}]' lastlogsize:null value:'CL#65ba5bcc-b679-4656-8a2e-5e28b08d889d:0:0:0:0:0
summary:0:0:0:0:0'`
разница между запросами - одна минута
Зависимость - ночью, когда нагрузка меньше - почти не проявляется, днём - рандомно.
Уже всё перерыл и всё передумал, где копать - хз. Единственная идея - техжурнал и там смотреть, но техжурнал не умею, поэтому пока тут.

**Comment by slothfk** [comment]
Вариант 1, увеличить таймаут в макросе `{$RAS_TMIEOUT}` (по-умолчанию 1.5 сек)
Вариант 2, увеличить таймаут агента заббикс (по-умолчанию 3 сек)

**Comment by IlyaSapytskiy** [comment]
> Вариант 1, увеличить таймаут в макросе `{$RAS_TMIEOUT}` (по-умолчанию 1.5 сек) Вариант 2, увеличить таймаут агента заббикс (по-умолчанию 3 сек)

именно таймаут макроса не заметил. Увеличил до 5с и всё нормализовалось
А таймаут агента всегда увеличиваю до 10с, но не помогло, поэтому и написал...
Спасибо!
