### ISSUE TITLE
Отладка: Элемент данных и триггеры

### ISSUE THREAD

**Issue by sirbusby** [slothfk/1c_zabbix_template_ce#93]
Прошу рассмотреть возможность доработки шаблона для возможности мониторинга включенной отладки. Добавить два триггера:
Включена отладка по tcp
Включена отладка по http
Часто включают отладку на продуктивных серверах и иногда это ведёт к деградации производительности или высокой нагрузке на процессор. 
![debug](https://user-images.githubusercontent.com/35493244/196649183-4f77919e-4468-42e5-aeb5-f4ab578289e0.png)

**Comment by slothfk** [comment]
> Включена отладка по tcp
> Включена отладка по http

Есть существенная разница с точки зрения наблюдения за фактом включения отладки? Т.е. отладка в продуктиве в любом случае плохо, и наверное не важно какого типа (или все же важно)?

Что именно хотелось бы "видеть" в контексте данной задачи? Просто факт "включено/нет" или что-то еще?

**Comment by sirbusby** [comment]
Отладка по http более проблемная. Сужу по собственному опыту и по сообщениям с партнерского форума. Если разделять трудоёмко , то хватит просто факта включения любого типа отладки.
