### ISSUE TITLE
Мониторинг блокировки начала сеансов

### ISSUE THREAD

**Issue by sirbusby** [slothfk/1c_zabbix_template_ce#94]
По аналогии с [Мониторинг блокировки регламентных заданий](https://github.com/slothfk/1c_zabbix_template_ce/issues/63) предлагаю сделать мониторинг блокировки начала сеансов. Почему то тогда мне эта идея в голову не пришла. Но как полазала практика это тоже необходимо.

**Comment by slothfk** [comment]
Так это было тогда же реализовано с блокировкой регламентных заданий! Мы уже этим активно пользуемся у себя ;)
