### ISSUE TITLE
[Windows] не получаю данные из-за ошибки cannot open file `/tmp/1c_infobase_cache'

### ISSUE THREAD

**Issue by andrew-ogonkov** [slothfk/1c_zabbix_template_ce#96]
Имею: на сервер - win2016_std
север 1с, платформа : 1c_8.3.18.1563
Поднимаю RAS сервер (от LocalSystem) , к нему через RAC подключаюсь и опрашиваю, в ответ получаю инфу по кластеру, базам, сессиям и пр., т.е. корректно работает служба.
Затем размещаю скрипты в папке zabbix - c:\zabbix\sripts
Устанавливаю gitbash. 
Выполняю: 
`bash -x 1c_central_server.sh sessions 2>session.log`
Получаю:
++ dirname 1c_central_server.sh
++ sed -r 's/\\/\//g; s/^(.{1}):/\/\1/'
+ WORK_DIR=.
+ source ./1c_common_module.sh
+ case ${1} in
+ shift
+ make_ras_params
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export RAS_PORT RAS_TIMEOUT RAS_AUTH
+ get_session_amounts
+ check_clusters_cache
+ readarray -t RMNGR_LIST
++ '[' -z 1 ']'
++ sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/'
++ wmic path win32_process where 'caption like '\''rphost%'\''' get CommandLine
++ sort -u
++ grep rphost
++ awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }'
+ echo Server1C:1541
+ [[ -e /tmp/1c_clusters_cache ]]
+ [[ '' == \l\o\s\t ]]
++ grep -vc '^$' /tmp/1c_clusters_cache
+ [[ 1 -ne 1 ]]
++ date -r /tmp/1c_clusters_cache +%s
++ date -d 'last hour' +%s
+ [[ 1670495191 -lt 1670495322 ]]
+ push_clusters_list Server1C:1541
+ cat /dev/null
+ execute_tasks push_clusters_uuid Server1C:1541
+ [[ 2 -le 1 ]]
+ TASK_CMD=push_clusters_uuid
+ shift
+ export -f push_clusters_uuid
+ echo Server1C:1541
+ xargs '-d ' -P4 -I task_args bash -c 'push_clusters_uuid ${@}' _ task_args
+ awk -F: -v OFS=: '{ print $0; 
            if ($1 !~ /^IB/) { sc["all"]+=$2; sc["bg"]+=$3; sc["hb"]+=$4; sc["ws"]+=$5; sc["hs"]+=$6; sc["as"]+=$7;
                if ( asd["cl"] < $8 ) { asd["cl"]=$8; } 
                if ( asd["bg"] < $9 ) { asd["bg"]=$9; } 
                if ( asd["ws"] < $10 ) { asd["ws"]=$10; } 
                if ( asd["hs"] < $11 ) { asd["hs"]=$11; } 
            } } 
            END { print "summary",sc["all"]?sc["all"]:0,sc["bg"]?sc["bg"]:0,sc["hb"]?sc["hb"]:0,\
                sc["ws"]?sc["ws"]:0,sc["hs"]?sc["hs"]:0,sc["as"]?sc["as"]:0,asd["cl"]?asd["cl"]:0,\
                asd["bg"]?asd["bg"]:0,asd["ws"]?asd["ws"]:0,asd["hs"]?asd["hs"]:0 }'
++ pop_clusters_list self
++ [[ ! -f /tmp/1c_clusters_cache ]]
+ sed 's/<sp>/ /g'
++ [[ -n self ]]
++ [[ self == \s\e\l\f ]]
++ sed 's/ /<sp>/g; s/"//g'
++ grep -i '^Server1C' /tmp/1c_clusters_cache
++ cut -d: -f2
+ execute_tasks get_clusters_sessions '11ac73e0-3f84-491a-abe3-96c74f06e7c9,1541,Local,cluster;'
+ [[ 2 -le 1 ]]
+ TASK_CMD=get_clusters_sessions
+ shift
+ export -f get_clusters_sessions
+ echo '11ac73e0-3f84-491a-abe3-96c74f06e7c9,1541,Local,cluster;'
+ xargs '-d ' -P4 -I task_args bash -c 'get_clusters_sessions ${@}' _ task_args
awk: cmd. line:2: fatal: cannot open file `/tmp/1c_infobase_cache' for reading (No such file or directory)

Что я делаю не так, помогите пожалуйста

**Comment by slothfk** [comment]
гляньте последний каммент в #95

**Comment by slothfk** [comment]
> гляньте последний каммент в #95
