### ISSUE TITLE
Базы видны, но данные с них не собираеются

### ISSUE THREAD

**Issue by Genius-GSM** [slothfk/1c_zabbix_template_ce#99]
Определяет список баз, но не собирает данные по ним.
![2023-01-31_12-34-24](https://user-images.githubusercontent.com/124041127/215725426-fa5ea7da-6e2b-4bfb-ac58-72b996c37cc5.png)

**Comment by slothfk** [comment]
Давайте подробности, на какой платформе это все? Это центральный сервер кластера?

**Comment by Genius-GSM** [comment]
> Давайте подробности, на какой платформе это все? Это центральный сервер кластера?

Ubuntu 20.04
1C 8.3.21.1644
Postgres Pro Ent 14
zabbix_agentd 6.0.12
zabbix_server 6.0.5

Так же вопрос, планируется ли переход на вторую версию zabbix агента? Или может есть инструкция как настроить на работу с ним?

**Comment by slothfk** [comment]
> Так же вопрос, планируется ли переход на вторую версию zabbix агента? Или может есть инструкция как настроить на работу с ним?

Не готов сказать со 100% гарантией, но там все так же с UserParameter, как и в агенте первой версии, должно работать

**Comment by slothfk** [comment]
> Ubuntu 20.04
> 1C 8.3.21.1644

Сервер 1С один в кластере?

**Comment by Genius-GSM** [comment]
> > Ubuntu 20.04
> > 1C 8.3.21.1644
> 
> Сервер 1С один в кластере?

нет, еще добавлен сервер лицензий на windows, но с него только лицензии, все остальное запрещено.

**Comment by slothfk** [comment]
В таком случае, пришлите вывод команды
```
$ bash -x 1c_central_server.sh sessions 1545 1.5 <cluster_admin> <cluster_password>
```
где `<cluster_admin>` и `<cluster_password>` имя и пароль администратора кластера в случае наличия такового?
А вообще много ли баз/сеансов на сервере?

**Comment by Genius-GSM** [comment]
Ответ:
summary:0:0:0:0:0:0:0:0:0:0

**Comment by slothfk** [comment]
> Ответ: summary:0:0:0:0:0:0:0:0:0:0 На сервере 4 базы и 150-200 сеансов

я просил указать `bash -x` перед именем скрипта ;)
Вывод странный, если у вас кластера определились, то и здесь должны быть строки начинающиеся с `CL#`

**Comment by Genius-GSM** [comment]
> > Ответ: summary:0:0:0:0:0:0:0:0:0:0 На сервере 4 базы и 150-200 сеансов
> 
> я просил указать `bash -x` перед именем скрипта ;) Вывод странный, если у вас кластера определились, то и здесь должны быть строки начинающиеся с `CL#`

Прошу прощения.
`++ dirname /var/lib/zabbix/scripts/1c_central_server.sh
++ sed -r 's/\\/\//g; s/^(.{1}):/\/\1/'
+ WORK_DIR=/var/lib/zabbix/scripts
+ source /var/lib/zabbix/scripts/1c_common_module.sh
+ case ${1} in
+ shift
+ make_ras_params 1545 1.5
+ [[ -n 1545 ]]
+ RAS_PORT=1545
+ [[ -n 1.5 ]]
+ RAS_TIMEOUT=1.5
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export RAS_PORT RAS_TIMEOUT RAS_AUTH
+ get_session_amounts
+ check_clusters_cache
+ readarray -t RMNGR_LIST
++ '[' -z ']'
++ pgrep -ax rphost
++ sed -r 's/.*-regport ([^ ]+).*/\0|\1/; s/.*-reghost ([^ ]+).*\|/\1:/'
++ sort -u
++ awk -F: '{ if ( clstr_list[$1]== "" ) { clstr_list[$1]=$2 } \
            else { clstr_list[$1]=clstr_list[$1]"|"$2 } } \
            END { for ( i in clstr_list ) { print i":"clstr_list[i]} }'
+ [[ -e /tmp/1c_clusters_cache ]]
+ [[ '' == \l\o\s\t ]]
++ grep -vc '^$' /tmp/1c_clusters_cache
+ [[ 1 -ne 0 ]]
+ push_clusters_list nc036srv:1541
+ cat /dev/null
+ execute_tasks push_clusters_uuid nc036srv:1541
+ [[ 2 -le 1 ]]
+ TASK_CMD=push_clusters_uuid
+ shift
+ export -f push_clusters_uuid
+ echo nc036srv:1541
+ xargs '-d ' -P32 -I task_args bash -c 'push_clusters_uuid ${@}' _ task_args
+ awk -F: -v OFS=: '{ print $0;
            if ($1 !~ /^IB/) { sc["all"]+=$2; sc["bg"]+=$3; sc["hb"]+=$4; sc["ws"]+=$5; sc["hs"]+=$6; sc["as"]+=$7;
                if ( asd["cl"] < $8 ) { asd["cl"]=$8; }
                if ( asd["bg"] < $9 ) { asd["bg"]=$9; }
                if ( asd["ws"] < $10 ) { asd["ws"]=$10; }
                if ( asd["hs"] < $11 ) { asd["hs"]=$11; }
            } }
            END { print "summary",sc["all"]?sc["all"]:0,sc["bg"]?sc["bg"]:0,sc["hb"]?sc["hb"]:0,\
                sc["ws"]?sc["ws"]:0,sc["hs"]?sc["hs"]:0,sc["as"]?sc["as"]:0,asd["cl"]?asd["cl"]:0,\
                asd["bg"]?asd["bg"]:0,asd["ws"]?asd["ws"]:0,asd["hs"]?asd["hs"]:0 }'
+ sed 's/<sp>/ /g'
++ pop_clusters_list self
++ [[ ! -f /tmp/1c_clusters_cache ]]
++ [[ -n self ]]
++ [[ self == \s\e\l\f ]]
++ sed 's/ /<sp>/g; s/"//g'
++ grep -i '^nc036srv' /tmp/1c_clusters_cache
++ cut -d: -f2
+ execute_tasks get_clusters_sessions
+ [[ 1 -le 1 ]]
+ exit
summary:0:0:0:0:0:0:0:0:0:0
`

**Comment by Genius-GSM** [comment]
/tmp/1c_clusters_cache кстати почему-т пустой.

**Comment by slothfk** [comment]
> /tmp/1c_clusters_cache кстати почему-т пустой.

Действительно странно, так как непонятно откуда взялись данные для обнаружения кластеров :/

А **ras** точно запущен?

**Comment by slothfk** [comment]
> /tmp/1c_clusters_cache кстати почему-т пустой.

удалите и запустите `1c_central_server.sh sessions ...`, опять пустым создастся?

**Comment by Genius-GSM** [comment]
> > /tmp/1c_clusters_cache кстати почему-т пустой.
> 
> удалите и запустите `1c_central_server.sh sessions ...`, опять пустым создастся?

сделал. файл снова создался пустой.

**Comment by slothfk** [comment]
> сделал. файл снова создался пустой.

а что возвращает
```
$ rac cluster list nc036srv:1545
```
на этой машине?

**Comment by Genius-GSM** [comment]
> 



> > сделал. файл снова создался пустой.
> 
> а что возвращает
> 
> ```
> $ rac cluster list nc036srv:1545
> ```
> 
> на этой машине?

 /opt/1cv8/x86_64/8.3.21.1644/rac cluster list nc036srv:1545
cluster                       : ff71a37e-0770-4db8-807f-c71cc4cfb6ac
host                          : nc036srv
port                          : 1541
name                          : "Local cluster"
expiration-timeout            : 60
lifetime-limit                : 86400
max-memory-size               : 0
max-memory-time-limit         : 0
security-level                : 0
session-fault-tolerance-level : 0
load-balancing-mode           : performance
errors-count-threshold        : 0
kill-problem-processes        : 1
kill-by-memory-with-dump      : 0

**Comment by slothfk** [comment]
> ++ dirname /var/lib/zabbix/scripts/1c_central_server.sh ++ sed -r 's/\///g; s/^(.{1})://\1/'
> 
>     * WORK_DIR=/var/lib/zabbix/scripts
> 
>     * source /var/lib/zabbix/scripts/1c_common_module.sh
> 
>     * case ${1} in

Пересмотрел еще раз, подскажите вы скрипты обовляли в существующей инсталяции?
Есть подозрение что скрипт `1c_common_module.sh` не актуальной версии ...

**Comment by Genius-GSM** [comment]
Может каких то прав доступа не хватать?

**Comment by slothfk** [comment]
Сомнительно, что дело в правах! Пока что-то идей, что можно посмотреть, нет ...

**Comment by slothfk** [comment]
Кажется я понял в чем дело, а пришлите ка вывод
```
$ awk --version
```

**Comment by Genius-GSM** [comment]
> awk --version

 awk --version
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
Copyright (C) 1989, 1991-2019 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.

**Comment by slothfk** [comment]
В таком случае интересен вывод
```
$ time /opt/1cv8/x86_64/8.3.21.1644/rac cluster list nc036srv:1545 | 
  awk -v FS=' +: +' '/^($|cluster|name|port)/ { if ($1){ print $2 } else {print "==="} }' | 
  awk -v FS='\n' -v RS='={3}\n' -v OFS=',' -v ORS=';' '$1=$1' 
```

**Comment by Genius-GSM** [comment]
> В таком случае интересен вывод
> 
> ```
> $ time /opt/1cv8/x86_64/8.3.21.1644/rac cluster list nc036srv:1545 | 
>   awk -v FS=' +: +' '/^($|cluster|name|port)/ { if ($1){ print $2 } else {print "==="} }' | 
>   awk -v FS='\n' -v RS='={3}\n' -v OFS=',' -v ORS=';' '$1=$1' 
> ```

ff71a37e-0770-4db8-807f-c71cc4cfb6ac,1541,"Local cluster",;
real    0m1,797s
user    0m1,217s
sys     0m0,576s

**Comment by slothfk** [comment]
> real 0m1,797s

Интересно, почему столь долгий ответ **ras**!?
Выходов несколько:
* разобраться с **ras** (например у меня ответ на этот запрос занимает `real    0m0.220s`)
* увеличить значение макроса `{$RAS_TIMEOUT}`, например до **3** секунд

**Comment by Genius-GSM** [comment]
> Интересно, почему столь долгий ответ **ras**!? Выходов несколько:
> 
> * разобраться с **ras** (например у меня ответ на этот запрос занимает `real    0m0.220s`)
> * увеличить значение макроса `{$RAS_TIMEOUT}`, например до **3** секунд

Спасибо. Именно этот вариант помог.
Увеличил значение макроса {$RAS_TIMEOUT}, до 3 секунд и данные пошли!
